### PR TITLE
[new_timepoint] only show null language option when multiple exist

### LINKED ISSUE #7997: [Manual testing] - New timepoint
**Describe the bug**
When creating a new timepoint, there is a null option in the language dropown menu.

### PR DESCRIPTION
**Pull request by CamilleBeau**
## Brief summary of changes
In this PR, the language drop down for timepoints is only contains a null option when creating a new timepoint if there are more than one languages to choose from in the language table. Otherwise the field automatically selected. 

- [x] Have you updated related documentation?

#### Testing instructions (if applicable)

1. Check that exactly one language exists in the language table
2. Create a new timepoint
3. Make sure that the language drop down does not contain a null option & that you are successfully able to create the timepoint with the one option automatically selected
4. Add a language to the language table to have 2 or more
5. Create another timepoint and make sure that the language drop down is displayed with a null option
6. Check that the language field is required in this case, and that you can not save without it
7. If the language selection is made, make sure that you are able to save the timepoint properly

#### Link(s) to related issue(s)

* Resolves #7997

### CODE REVIEW

File: modules/create_timepoint/jsx/createTimepointIndex.js [hunk 1]
```diff
@@ -150,7 +150,7 @@ class CreateTimepoint extends React.Component {
             this.handleVisitLabel();
           }
           // Populate the select options for languages.
-          if (data.languages) {
+          if (Object.keys(data.languages).length > 1) {
             state.form.options.languages = data.languages;
             state.form.display.languages = true;
```
Comment (maltheism) [inline modules/create_timepoint/jsx/createTimepointIndex.js:155]: Hi @CamilleBeau you could just modify line 155 to be:
`state.form.display.languages = Object.keys(data.languages).length > 1;`
then the form options on line 154 would still contain the data.languages if it's ever needed when there's only 1 option available and while languages on the form are still being hidden to the user.

Comment (CamilleBeau) [reply modules/create_timepoint/jsx/createTimepointIndex.js]: Done!

**Review by zaliqarosli — CHANGES_REQUESTED** [review]
with only 1 language, the field still displays

**Comment by CamilleBeau** [comment]
> with only 1 language, the field still displays

Sorry Zaliqa, I fixed the PR title & description. The PR was modified so that the field still displays but a null option is only present when multiple languages exist.

**Comment by zaliqarosli** [comment]
for step 1 "Check that one or less languages exists in the language table", whats the intended functionality if there are 0 languages in the language table?

**Comment by CamilleBeau** [comment]
> for step 1 "Check that one or less languages exists in the language table", whats the intended functionality if there are 0 languages in the language table?

This is a mistake - there should be at least one language. Fixed step 1

**Comment by zaliqarosli** [comment]
@CamilleBeau okayy looks good! could you add the changes in this PR to the Testplan.md? and then i'll approve!

**Comment by CamilleBeau** [comment]
> @CamilleBeau okayy looks good! could you add the changes in this PR to the Testplan.md? and then i'll approve!

Done!

File: modules/create_timepoint/test/TestPlan.md [hunk 2]
```diff
@@ -40,6 +40,10 @@ visit label already exists for the candidate.
 successful form submission. Click on "Ok" button and ensure that it brings you back
 to timepoint list page for that candidate and confirm that the new timepoint appears in the list.
   [Manual Testing]
-14. Check that page is inaccessible if either the user does not have data_entry
+14. Ensure that there is no null value and a language is automatically selected when only one 
+language exists in the `language` table.
+15. Ensure that there is a null value and the language field is required when more than one
```
Comment (zaliqarosli) [inline modules/create_timepoint/test/TestPlan.md:45]:
```suggestion
14. Ensure that there is an empty option in the language select element and a language is automatically selected when only one 
language exists in the `language` table.
15. Ensure that there is an empty option in the language select element and the field is required when more than one 
```

**Review by zaliqarosli — CHANGES_REQUESTED** [review]

**Review by zaliqarosli — APPROVED** [review]
