### PR TITLE
[RaisinBread] Adding instructions on how to delete the RB tables

### LINKED ISSUE #4990: Raisinbread DROP TABLES patch does not clear test instruments
Following the instructions to install a Raisinbread DB, I got an error:

`ERROR 1050 (42S01) at line 3024: Table 'aosi' already exists`

even after sourcing `SQL/9999-99-99-drop_tables.sql`.

This table is created by Raisinbread so I think the drop script should also remove it in order for a clean install/uninstall workflow.

### PR DESCRIPTION
**Pull request by cmadjar**
## Brief summary of changes

This includes instructions on how to delete a RB dataset when needing to empty a database with the RB dataset. It includes a patch to delete first the instrument tables and then uses the already existant `9999-99-99-drop_tables.sql` in the SQL directory.

#### Testing instructions (if applicable)

1. Try running the delete instructions in the README.md and check that all tables from the RB dataset were removed.

#### Links to related tickets (GitHub, Redmine, ...)

* Resolves #4990

### CODE REVIEW

**Comment by cmadjar** [comment]
@johnsaigle I added you as a reviewer since you created the issue. (I already created the patch last week but never sent the PR... When I saw your issue, I figured it might be a good idea to send it ;) )

File: raisinbread/instruments/instrument_sql/9999-99-99-drop_instrument_tables.sql [hunk 1]
```diff
@@ -0,0 +1,7 @@
+-- Drop RB instrument tables
+DROP TABLE IF EXISTS `aosi`;
+DROP TABLE IF EXISTS `bmi`;
+DROP TABLE IF EXISTS `medical_history`;
+DROP TABLE IF EXISTS `mri_parameter_form`;
+DROP TABLE IF EXISTS `radiology_review`;
+DROP TABLE IF EXISTS `testtest`;
```
Comment (ridz1208) [inline raisinbread/instruments/instrument_sql/9999-99-99-drop_instrument_tables.sql]: testtest was removed from the creation instructions so it can be removed from here as well, only travis will use it

**Comment by johnsaigle** [comment]
Thank you!

File: raisinbread/instruments/instrument_sql/9999-99-99-drop_instrument_tables.sql (hunk 1 above)
Comment (cmadjar) [reply raisinbread/instruments/instrument_sql/9999-99-99-drop_instrument_tables.sql]: Done in the next commit!

**Comment by cmadjar** [comment]
Loved your comment @ridz1208! The testtest was removed from the patch. Thanks!

Thanks @johnsaigle for testing it!
