### PR TITLE
[configuration] adds confirmation prompt when deleting a field.

### LINKED ISSUE #7010: [configuration] Button for deleting an added field (for a field that has the "Add field" functionality) not behaving as expected.
**Describe the bug**
The "X" Button for deleting an added field (for a field that has the "Add field" functionality) is not behaving as expected.

**To Reproduce**
1. Go to `MainMenu-> Admin -> Configuration -> Statistics.`
2. Click on the `"X" button` for an already submitted(existing) field.
3. As result the field is deleted permanently immediately (refresh the page to note)  

**What did you expect to happen?**
According to the Test Plan the user should click submit for this action to be committed. In other case it could be convenient to make aware the user the action is permanent and immediate.

### PR DESCRIPTION
**Pull request by racostas**
## Brief summary of changes

Adds confirmation prompt when deleting a field.
See more details on issue #7010 

- [x] Have you updated related documentation?
Test Plan updated.

#### Testing instructions

1. Go to `MainMenu-> Admin -> Configuration -> Statistics.`
2. Click on the **"X"** button for an already submitted(existing) field.
3. A dialog box should ask for delete confirmation before proceeding.

#### Link to related issue

* Resolves #7010

### CODE REVIEW

**Comment by cmadjar** [comment]
@racostas could you please rebase so the tests can run?

@zaliqarosli could you review this PR once rebased please? Thank you!

File: modules/configuration/js/configuration_helper.js [hunk 1]
```diff
@@ -39,31 +39,44 @@ $(function () {
...
 
-        var id = $(this).attr('name');
-        var button = this;
+        var options        = $(this).parent().parent().children().prop('options');
+        var selectedIndex  = $(this).parent().parent().children().prop('selectedIndex');
+        var selectedOption = options[selectedIndex].text;
+        var fieldName      = $(this).parent().parent().parent().parent().parent().children().attr('data-original-title');
+
+        if(
+            window.confirm(
```
Comment (zaliqarosli) [inline modules/configuration/js/configuration_helper.js:48]: i'm having trouble getting my dev vm front-end working so i haven't seen what this dialogue box looks like. any chance you can add a screenshot to this PR? I'm wondering if using swal would work here so that the UI matches with the rest of LORIS

**Review by zaliqarosli — CHANGES_REQUESTED** [review]

File: modules/configuration/js/configuration_helper.js (hunk 1 above)
Comment (racostas) [reply modules/configuration/js/configuration_helper.js:48]: Hi @zaliqarosli. Thank you for your comments. This is the way it looks in the UI.  

image

Comment (zaliqarosli) [reply modules/configuration/js/configuration_helper.js:48]: @racostas could you try implementing a swal (sweetalert2) ?

Comment (racostas) [reply modules/configuration/js/configuration_helper.js:48]: Hi @zaliqarosli, I'm not familiarized with the library but will try to give it a try.

Comment (zaliqarosli) [reply modules/configuration/js/configuration_helper.js:48]: @racostas you can look for how it is being used elsewhere in loris and refer to the docs here https://sweetalert2.github.io/

Comment (racostas) [reply modules/configuration/js/configuration_helper.js:48]: Hi @zaliqarosli, I'm still getting issues having the sweetalert2 properly working. It's seem the`LORIS configuration module` (the one we're modifying) * is not yet Reactified.

I'm trying Importing `sweetalert2` from the` project.js` page `/var/www/loris/modules/configuration/js/project.js` don't seems to work. Its not getting imported.

I think I should be missing something obvious but my experience with JS is not that extensive. If you can give me any insight will be very helpful. Thanks.

Comment (zaliqarosli) [reply modules/configuration/js/configuration_helper.js:48]: @racostas i will check out your branch and play around. i'll let you know!

Comment (zaliqarosli) [reply modules/configuration/js/configuration_helper.js:48]: hey @racostas it looks like sweetalert2 only works within React components which this js file is not. we do have sweetalert library in htdocs/vendor but we are trying to remove that. so I think until we reactify the configuration module, your implementation is the best option!

**Comment by cmadjar** [comment]
@zaliqarosli could you re-review please? Thanks!

File: modules/configuration/js/configuration_helper.js (hunk 1 above)
Comment (zaliqarosli) [reply modules/configuration/js/configuration_helper.js:48]: @laemtl do you have solutions for us?

**Comment by zaliqarosli** [comment]
status update: @laemtl may have a solution for us (to use sweetalert2 on non-react module). i will re-review after this has been implemented

File: modules/configuration/js/configuration_helper.js (hunk 1 above)
Comment (laemtl) [reply modules/configuration/js/configuration_helper.js:48]: @zaliqarosli @racostas  I have a working solution ready to be pushed. I just need permission to push on @racostas's branch.

**Comment by laemtl** [comment]
@zaliqarosli Fix is ready and waiting for permission to push.

**Comment by racostas** [comment]
Go ahead @laemtl ! Thank you.

**Comment by laemtl** [comment]
@cmadjar pushed.

**Comment by laemtl** [comment]
@racostas I fixed a conflict with a rebase.

**Comment by laemtl** [comment]
@racostas There is an integration test to fix.

**Comment by zaliqarosli** [comment]
@laemtl thanks for the contribution! is this ready to test? I'm wondering if `modules/configuration/js/configuration_helper.js ` can be completely removed given the new jsx file?

**Comment by laemtl** [comment]
@zaliqarosli Yes, ready to test! And thanks for letting me know about the duplicates, it was a mistake.

**Review by zaliqarosli — CHANGES_REQUESTED** [review]
add `js/configuration_helper.js` to the .gitignore file, but besides that, everythings great!

**Comment by laemtl** [comment]
@zaliqarosli .gitignore updated!

**Review by zaliqarosli — APPROVED** [review]
LGTM

**Comment by laemtl** [comment]
@driusan No tests have run successfully for a couple of days now. They need to be fixed, unrelated to this PR.
