### PR TITLE
[Tests] Integration tests Fix

### LINKED ISSUE #6781: [Integration tests] Running Integration tests executes the Unit Tests suite
Since #5635, running `npm run tests:integration` executes the unit tests. 
This is fixed by reverting the change made in test/dockerized-integration-tests.sh and adding back --testsuite LorisModuleIntegrationTests $*

### PR DESCRIPTION
**Pull request by laemtl**
Fix a regression introduced in #5635 which prevents integration tests to be run with `npm run tests:integration`

* Resolves #6781

### CODE REVIEW

File: test/dockerized-integration-tests.sh [hunk 1]
```diff
@@ -9,4 +9,4 @@ else
 fi
 
 # Core integration tests
-docker-compose run -T -e HEADLESS=true --rm ${CONTAINER} vendor/bin/phpunit --configuration test/phpunit.xml
+docker-compose run -T -e HEADLESS=true --rm ${CONTAINER} vendor/bin/phpunit --configuration test/phpunit.xml --testsuite LorisModuleIntegrationTests $*
```
Comment (kongtiaowang) [inline test/dockerized-integration-tests.sh:12]: This way will miss LorisCoreIntegrationTests as well.
Please add LorisCoreIntegrationTests into this file.

Comment (laemtl) [reply test/dockerized-integration-tests.sh:13]: @kongtiaowang It's done!
