### PR TITLE
[configuration] Use unsafeInsert/unsafeUpdate for saving values

### LINKED ISSUE #8748: [configuration module] - Study description issue
**Describe the bug**
A clear and concise description of what the bug is
When updating the study description in the configuration module the value saved is escaped. 
image

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):

**What did you expect to happen?**

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

### PR DESCRIPTION
**Pull request by driusan**
The values get double-escaped when modified now if they contain HTML. Use unsafe variants of database calls so that the values to not get modified when re-saved.

Fixes #8748

### CODE REVIEW

File: modules/configuration/ajax/process.php [hunk 1]
```diff
@@ -60,7 +60,7 @@
                 }
             }
             // Update the config setting to the new value.
-            $DB->update(
+            $DB->unsafeUpdate(
```
Comment (zaliqarosli) [inline modules/configuration/ajax/process.php:63]: is this okay to change for all update/inserts on the config module, not knowing what other front-end values this might affect?

Comment (driusan) [reply modules/configuration/ajax/process.php:63]: I looked on demo and only saw 3 textarea config settings:

1. The studyDescription used on the login page. This already uses DOMPurify to make sure the value is clean.
2. The projectDescription used by the dashboard welcome widget. An admin would be able update the description to include unsafe HTML there, but this is addressed by PR #8762. 
3. The citation_policy used by the acknowledgements module. This is used by the acknowledgements module inside of a React component, so it should be auto-escaped by React.

**Review by zaliqarosli — APPROVED** [review]
