### PR TITLE
[Tools] delete_candidate CanID Fix

### LINKED ISSUE #6757: delete_candidate.php should use CandID class
**Describe the Problem**
delete_candidate.php tool has not been updated to use CandID class and throws an error in newer versions of LORIS. 

**Suggested Action**
Add `use LORIS\StudyEntities\Candidate\CandID;` at the beginning of the file. Replace `$candID = $argv[2];` with `$candID = new CandID($argv[2]);`

### PR DESCRIPTION
**Pull request by laemtl**
Fix in delete_candidate.php tool to use the CandID class.

* Resolves #6757

### CODE REVIEW

File: tools/delete_candidate.php [hunk 1]
```diff
@@ -150,7 +154,7 @@ function showHelp()
  * (second-level relations) should have actions on delete specified in the
  * database schema
  *
- * @param string   $CandID     Identifying the candidate
+ * @param CanID    $CandID     Identifying the candidate
```
Comment (driusan) [inline tools/delete_candidate.php:157]:
```suggestion
 * @param CandID   $CandID     Identifying the candidate
```

File: tools/delete_candidate.php [hunk 2]
```diff
@@ -18,11 +18,15 @@
  * @license  Loris license
  * @link     https://www.github.com/aces/Loris-Trunk/
  */
+
+use LORIS\StudyEntities\Candidate\CandID;
```
Comment (driusan) [inline tools/delete_candidate.php:22]: I'm pretty sure this needs to go below the autoload require.

File: tools/delete_candidate.php [hunk 3]
```diff
@@ -18,11 +18,15 @@
  * @license  Loris license
  * @link     https://www.github.com/aces/Loris-Trunk/
```
Comment (christinerogers) [inline tools/delete_candidate.php:19]:
```suggestion
 * @link     https://www.github.com/aces/Loris/
```
cleanup

File: tools/delete_candidate.php (hunk 2 above)
Comment (laemtl) [reply tools/delete_candidate.php:22]: @driusan For my personal knowledge, can you explain a bit why? I will take that into account fot future changes.

Comment (driusan) [reply tools/delete_candidate.php:22]: I might be mistaken, it might not try autoloading until the class is referenced with "new", but how would the class be loaded if the autoloader hasn't been setup yet?

File: tools/delete_candidate.php (hunk 3 above)
Comment (driusan) [reply tools/delete_candidate.php]: @laemtl

**Comment by laemtl** [comment]
Thanks @ridz1208
