### PR TITLE
[tools/install.sh] fix for other operating systems

### LINKED ISSUE #5262: [tools/install.sh] broken on macOS
Latest changes to the install.sh script on minor has broken the script on macOS.

Output after running the script:

> ./install.sh: line 156: hostnamectl: command not found

### PR DESCRIPTION
**Pull request by maltheism**
## Brief summary of changes

Allows the shell script to continue if the command "hostnamectl" is not found.
Note: Let me know if the else statement is unnecessary.

#### Testing instructions (if applicable)

1. Test on macOS
2. Test on Ubuntu or centOS

#### Links to related tickets (GitHub, Redmine, ...)

* Fixes #5262

See other PR: #5286

### CODE REVIEW

File: tools/install.sh [hunk 1]
```diff
@@ -149,10 +149,15 @@ chmod 770 ../smarty/templates_c
 
 # Changing group to 'www-data' or 'apache' to give permission to create directories in Document Repository module
 # Detecting distribution
-os_distro=$(hostnamectl |awk -F: '/Operating System:/{print $2}'|cut -f2 -d ' ')
+if ! os_distro=$(hostnamectl 2>/dev/null)
+then
+  os_distro="other"
```
Comment (johnsaigle) [inline tools/install.sh]:
```suggestion
  os_distro="Other"
```

Otherwise the error message reads "other Linux distribution detected..." which looks a bit messy.

**Comment by johnsaigle** [comment]
Can you close the other PR? (#5286)
