### PR TITLE
Survey Module Validation Fix

### LINKED ISSUE #9086: [survey_accounts] Mismatched emails lock the form
**Describe the bug**
When emailing a survey, if you enter mismatch emails the Email button is disabled but the form is not sent out, no error message displayed

image

### PR DESCRIPTION
**Pull request by sruthymathew123**
#### Link(s) to related issue(s)

* Resolves #9086

### CODE REVIEW

**Comment by sruthymathew123** [comment]
@ridz1208 I made some changes to the validation. Let me know if you still see any issues.

File: modules/survey_accounts/js/survey_accounts_helper.js [hunk 1]
```diff
@@ -39,7 +39,10 @@ $(document).ready(function () {
                 $('#create_survey').removeAttr('disabled');
                 $('#email_survey').attr('disabled','disabled');
             }
-
+            if (email.length > 0 && email2.length > 0 && email !== email2)
```
Comment (driusan) [inline modules/survey_accounts/js/survey_accounts_helper.js:42]: Shouldnt this (and the one above) be

```
if ((email.length > 0 || email2.length > 0) && email !== email2)
```

?

Comment (sruthymathew123) [reply modules/survey_accounts/js/survey_accounts_helper.js:42]: @driusan First condition(above of this) is to disable the Email Survey Button.  if (email2.length == 0 || email.length == 0 || email != email2) , disable Email Survey Button if any of the condition is true.

if (email.length > 0 && email2.length > 0 && email !== email2) -> this is for the correct error message to pop up when both email and confirm email have values and not matching.

Comment (driusan) [reply modules/survey_accounts/js/survey_accounts_helper.js:42]: Oh, my bad. GitHub was hiding that part of the code unless I manually expanded it.
