### PR TITLE
Remove lorispath from PSR7 request

### LINKED ISSUE #9049: lorispath leaks into PSR7 request on Apache server
**Describe the bug**

The URL modification by `mod_rewrite`, which transforms `loris.ca/foo/bar` into `loris.ca?lorispath=foo/bar`, seems to leak into `$_SERVER` and consequently into the PSR7 `$request` object on Apache server. This means that `lorispath` is accessible in `getQueryParams()` and more importantly that `$request->getUri()->__toString()` is not usable to get the current request URL.

**To Reproduce**

1. Have a setup with Apache server
2. Inspect the PSR7 `$request` object.

We reproduced this behaviour on both my's and @ridz1208's machines.

**Thoughts**

I am not sure yet what are the possible fixes to this unintended behaviour. Either way, here are the potential solutions I could think of:
1. Change the Apache/PHP configuration to prevent the rewritten URL from leaking.
2. Manually create the `$request` object to use the original request URL.
3. Do not rewrite the URL (if possible).
4. Ignore the leak (the original URL is still accessible in `$_SERVER['REQUEST_URI']`).

### PR DESCRIPTION
**Pull request by MaximeMulder**
## Brief summary of changes

Removes `lorispath` from the PSR7 request's query parameters and uri query string (both must be updated separately).
Manipulating arrays in PHP is so verbose 😴.

#### Testing instructions

var dump `$serverrequest`

#### Links to related issues

* Resolves #9049
* Enables #9041

### CODE REVIEW

File: htdocs/index.php [hunk 1]
```diff
@@ -41,6 +41,24 @@
...
+$serverrequest = $serverrequest->withQueryParams($params);
+
+$query = implode(
+    "&",
+    array_map(
+        fn ($key, $value) => $key . "=" . $value,
+        array_keys($params),
+        $params
+    )
+);
```
Comment (MaximeMulder) [inline htdocs/index.php:57]: I did not use `http_build_query` because the parameters should already be URL-encoded.

File: htdocs/index.php [hunk 2]
```diff
@@ -41,6 +41,24 @@
 
 $serverrequest = \Laminas\Diactoros\ServerRequestFactory::fromGlobals();
 
+// Remove the lorispath from the URI query parameters.
+// Both the request query parameters and the URI query string must be updated.
+$params        = $serverrequest->getQueryParams();
+$params        = array_diff_key($params, ["lorispath" => null]);
```
Comment (driusan) [inline htdocs/index.php:47]:
```suggestion
unset($params['lorispath']);
```

File: htdocs/index.php (hunk 1 above)
[the remark this answers is not in the document]
Comment (driusan) [reply htdocs/index.php:57]: Is this necessary? Shouldn't it have been handled internally `$serverrequest = $serverrequest->withQueryParams($params);`?

[the remark this answers is not in the document]
Comment (MaximeMulder) [reply htdocs/index.php:57]: > Is this necessary? Shouldn't it have been handled internally by the library after `$serverrequest = $serverrequest->withQueryParams($params);`?

Yes it is, the request stores both the query parameters as an array and as a string in the URI. Changing one does not affect the other.

File: htdocs/index.php (hunk 2 above)
Comment (MaximeMulder) [reply htdocs/index.php]: TIL PHP arrays are copy-on-write.
Applied.
