### PR TITLE
[Raisinbread] Removed references to Reliability module

### LINKED ISSUE #5876: Remove references to Reliability module from Raisinbread
**Describe the bug**
Reliability doesn't exist anymore but its data is still present in Raisinbread

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
Screen Shot 2019-12-17 at 17 50 44

**What did you expect to happen?**
Reliability data should be removed.

**Additional context**
#3886

### PR DESCRIPTION
**Pull request by AlexandraLivadas**
I removed references to the Reliabilty module in the Raisinbread permissions table. I looked for other references to Reliability throughout Raisinbread and other SQL patches and did not find any more that needed to be deleted.

#### Testing instructions 

With a fresh RB install:

1. Use the query `SELECT * FROM permissions;` in your database to see that there are no reliability permissions.

* Resolves #5876

### CODE REVIEW

**Comment by ridz1208** [comment]
@AlexandraLivadas are these permissions still in the main schema ? if not was there a patch to remove them from projects ?

(I generally avoid manipulating RB directly. theoretically anything in RB is still there because no LORIS release patch addressed the changes. In this case, it might mean that no LORIS release patch deleted the permissions for existing projects and thats why they still exist in RB)

**Comment by AlexandraLivadas** [comment]
> @AlexandraLivadas are these permissions still in the main schema ? if not was there a patch to remove them from projects ?
> 
> (I generally avoid manipulating RB directly. theoretically anything in RB is still there because no LORIS release patch addressed the changes. In this case, it might mean that no LORIS release patch deleted the permissions for existing projects and thats why they still exist in RB)

@ridz1208 When I did an initial look-through of all the main SQL files and Raisinbread files, I didn't see anything about the Reliability module beyond a few patches from many releases ago. I'll take a deeper look though and get back to you.

**Comment by AlexandraLivadas** [comment]
@ridz1208 There are no release patches that specifically address reliability permissions, which is probably why this still exists in Raisinbread. These permissions are not still in the main schema. Should I make a patch to delete these entries or should I modify Raisinbread by doing an SQL dump?

**Comment by ridz1208** [comment]
@AlexandraLivadas both basically. Theoretically you should create a patch and run it on RB and then export RB and submit the changes in your Pr. the changes to RB will/should look exactly like the ones you currently have but might also include the deletion from user_perm_rel for the permissions being deleted...

File: raisinbread/RB_files/RB_files.sql [hunk 1]
```diff
@@ -1,316 +1,316 @@
 SET FOREIGN_KEY_CHECKS=0;
 TRUNCATE TABLE `files`;
 LOCK TABLES `files` WRITE;
-INSERT INTO `files` (`FileID`, `SessionID`, `File`, `SeriesUID`, `EchoTime`, `CoordinateSpace`, `OutputType`, `AcquisitionProtocolID`, `FileType`, `InsertedByUserID`, `InsertTime`, `SourcePipeline`, `PipelineDate`, `SourceFileID`, `ProcessProtocolID`, `Caveat`, `TarchiveSource`, `ScannerID`, `AcqOrderPerModality`) VALUES (134,1053,'assembly/587630/V1/mri/native/demo_587630_V1_t1_001.mnc','1.3.12.2.1107.5.2.32.35008.2009052710234557661341584.0.0.0',0.00316,'native','native',44,'mnc','cecile',1558633727,NULL,NULL,NULL,NULL,0,27,1,1);
```
Comment (driusan) [inline raisinbread/RB_files/RB_files.sql:4]: I don't see why this file is modified here.. it doesn't look like the patch should affect it.

Comment (AlexandraLivadas) [reply raisinbread/RB_files/RB_files.sql:4]: I was confused about that as well. I used the `DB_dump_table_data.php` tool to extract the changes to raisinbread and for some reason this was included in the changes. I can remove this file from the PR just in case.

Comment (driusan) [reply raisinbread/RB_files/RB_files.sql:4]: @ridz1208 thoughts?

Comment (ridz1208) [reply raisinbread/RB_files/RB_files.sql:4]: the `HrrtArchiveID` column was removed at the same time as the changes were made

most likely removed in another PR and forgot to remove it from RB.

running the patch and exporting the dataset revealed the changes

Comment (AlexandraLivadas) [reply raisinbread/RB_files/RB_files.sql:4]: Hm ok. Should I try a fresh install of RB then and re-run the patch? Or would that not make a difference?

Comment (ridz1208) [reply raisinbread/RB_files/RB_files.sql:4]: @AlexandraLivadas that would not work since the column is now in the schema, it will always be automatically created when you resource RB. That column was added 22 days ago in #6142 

You could simply checkout the changes from this Pr. basically just ignore that file when submitting the changes. Another PR should be issue to apply the patch found in #6142 on RB

Comment (AlexandraLivadas) [reply raisinbread/RB_files/RB_files.sql:4]: Ok I can do that. I can also make the PR to apply the patch from #6142 today.

Comment (ridz1208) [reply raisinbread/RB_files/RB_files.sql:4]: @AlexandraLivadas that would be great.

one caveat to keep in mind however is the following. Because the PR creating the column was merged without the RB update going with it, you will find that the patch in the PR might fail when trying to create a column that already exists (because it was sourced from the schema). I have found that the easiest thing to do is to simply remove the `ADD column` command from the patch and any `ADD constraint` that might also fail for duplication before running the patch...

if it gets too complicated, let me know I can assist

Comment (AlexandraLivadas) [reply raisinbread/RB_files/RB_files.sql:4]: Ok thanks, I will let you know! For this PR, I can try to re-apply the patch with a fresh RB install and just ignore any files not related to this, but I should also try to get rid of the changes made to `RB_files.sql`, correct?

Comment (ridz1208) [reply raisinbread/RB_files/RB_files.sql:4]: depends you you are going at it. basically if you start from scratch, after running export_DB simply checkout any "unrelated" changes. if you wanna save this PR. simply reset to HEAD the files that are not supposed to be changed.

Comment (AlexandraLivadas) [reply raisinbread/RB_files/RB_files.sql:4]: Ok sounds good! Thank you

Comment (ridz1208) [reply raisinbread/RB_files/RB_files.sql:4]: Also, when you apply a new patch or a cleanup patch to RB you can enter the name of the patch in the [migration log](https://github.com/aces/Loris/blob/main/raisinbread/migration.md) this helps identify if the RB dataset has fallen behind. up until now I was mostly handling that part but any help is appreciated.

Comment (AlexandraLivadas) [reply raisinbread/RB_files/RB_files.sql:4]: Ok I will add that in this PR as well as the one I make for #6142

File: raisinbread/RB_files/RB_user_perm_rel.sql [hunk 2]
```diff
@@ -26,8 +26,6 @@ INSERT INTO `user_perm_rel` (`userID`, `permID`) VALUES (1,22);
 INSERT INTO `user_perm_rel` (`userID`, `permID`) VALUES (1,23);
 INSERT INTO `user_perm_rel` (`userID`, `permID`) VALUES (1,24);
 INSERT INTO `user_perm_rel` (`userID`, `permID`) VALUES (1,25);
-INSERT INTO `user_perm_rel` (`userID`, `permID`) VALUES (1,26);
-INSERT INTO `user_perm_rel` (`userID`, `permID`) VALUES (1,27);
 INSERT INTO `user_perm_rel` (`userID`, `permID`) VALUES (1,28);
```
Comment (kongtiaowang) [inline raisinbread/RB_files/RB_user_perm_rel.sql:29]:
```suggestion
INSERT INTO `user_perm_rel` (`userID`, `permID`) VALUES (1,26);
```

Comment (kongtiaowang) [reply raisinbread/RB_files/RB_user_perm_rel.sql:29]: @AlexandraLivadas You need to re-order the permIDs after you remove the 26 and 27.

File: raisinbread/RB_files/RB_permissions.sql [hunk 3]
```diff
@@ -25,8 +25,6 @@ INSERT INTO `permissions` (`permID`, `code`, `description`, `categoryID`) VALUES
 INSERT INTO `permissions` (`permID`, `code`, `description`, `categoryID`) VALUES (23,'imaging_browser_view_site','View own-site Imaging Browser pages',2);
 INSERT INTO `permissions` (`permID`, `code`, `description`, `categoryID`) VALUES (24,'imaging_browser_view_allsites','View all-sites Imaging Browser pages',2);
 INSERT INTO `permissions` (`permID`, `code`, `description`, `categoryID`) VALUES (25,'dicom_archive_view_allsites','Across all sites view Dicom Archive module and pages',2);
-INSERT INTO `permissions` (`permID`, `code`, `description`, `categoryID`) VALUES (26,'reliability_edit_all','Access and Edit all Reliability profiles',2);
-INSERT INTO `permissions` (`permID`, `code`, `description`, `categoryID`) VALUES (27,'reliability_swap_candidates','Swap Reliability candidates across all sites',2);
 INSERT INTO `permissions` (`permID`, `code`, `description`, `categoryID`) VALUES (28,'instrument_builder','Instrument Builder: Create and Edit instrument forms',2);
```
Comment (kongtiaowang) [inline raisinbread/RB_files/RB_permissions.sql:28]: You need to re-order the permIDs after you remove the 26 and 27.
