### PR TITLE
[behavioural_qc] Resolving redirect to conflict resolver issue

### LINKED ISSUE #7159: [23.0][behavioural_qc] Link does not redirect to conflict resolver
**Describe the bug**
Link to conflict resolver does not work.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `Behavioural Quality Control` module
2. Click on `Data Conflicts` tab
3. Click on any instrument

**What did you expect to happen?**
Should redirect to the `Conflict Resolver` with filters set to show the specific instrument / candidate you clicked on.

### PR DESCRIPTION
**Pull request by HenriRabalais**
## Brief summary of changes
This PR fixes a bug in the Behavioural QC module. The issue was that clicking on link in the `Instrument` column of the `Data Conflicts` tab would redirect to the Conflict Resolver module, but would not include the appropriate filters.

#### Testing instructions
1. Go to Behaviour QC Module
2. Click on Data Conflicts Tab
3. Click on link in the Instruments column
4. Ensure that you are redirected to the Conflict Resolver module with the appropriate filters applied

#### Link to related issue
* Resolves #7159

### CODE REVIEW

**Comment by HenriRabalais** [comment]
Assigning @ridz1208 in accordance with @cmadjar's email.

File: modules/behavioural_qc/jsx/behavioural_qc_module.js [hunk 1]
```diff
@@ -199,12 +199,8 @@ class InstrumentConflictsRow extends Component {
...
           </td>
         <td>
-          <a href="#" onClick={loris.loadFilteredMenuClickHandler(
-                 'conflict_resolver/',
-                  {CandID: row.CandID,
-                  Instrument: row.TableName,
-                  Question: row.FieldName}
-          )}>{row.test_name_display}</a>
+          <a href={baseURL + '/conflict_resolver/?pSCID=' + row.PSCID +
+           '&instrument=' + row.TableName}>{row.test_name_display}</a>
```
Comment (driusan) [inline modules/behavioural_qc/jsx/behavioural_qc_module.js:203]: This seems to have lost the field name part of the filter

Comment (HenriRabalais) [reply modules/behavioural_qc/jsx/behavioural_qc_module.js]: could catch
