### PR TITLE
[login/request account] Weird ordering of projects in dropdown

### LINKED ISSUE #7790: [login/request account] Weird ordering of projects in dropdown
**Describe the bug**
when requesting a new account the dropdown for projects displays the first option BEFORE the "choose you project:" placeholder (see image)
Screen Shot 2021-11-05 at 1 22 40 PM

### PR DESCRIPTION
**Pull request by maltheism**
## Brief summary of changes

Solves the incorrect order of dropdowns of select when no label is being used for login design.

#### Link(s) to related issue(s)

* Resolves #7790

Preview of change:

Screen Shot 2021-11-05 at 2 33 28 PM
Screen Shot 2021-11-05 at 2 33 36 PM

### CODE REVIEW

File: jsx/Form.js [hunk 1]
```diff
@@ -653,6 +659,7 @@ SelectElement.propTypes = {
   errorMessage: PropTypes.string,
   onUserInput: PropTypes.func,
   noMargins: PropTypes.bool,
+  selectLabel: PropTypes.string,
```
Comment (ridz1208) [inline jsx/Form.js:662]: @maltheism ccan you rename it `placeholder` instead

Comment (maltheism) [reply jsx/Form.js]: @ridz1208 updated

**Review by ridz1208 — APPROVED** [review]

**Comment by ridz1208** [comment]
@maltheism it looks good for this specific usecase, the only issue is the option is disabled. so on a different form, in a different context, you might wanna be able to go back to the placeholder in case you dont want to select an option for this dropdown

**Comment by maltheism** [comment]
@ridz1208 I could solve that by having a prop to enable placeholder or disable placeholder. Something like placeholderDisable?

**Comment by ridz1208** [comment]
I think you could leave placeholder always enabled

**Comment by maltheism** [comment]
@ridz1208 done

**Comment by ridz1208** [comment]
@maltheism beautiful!! work of art

**Comment by ridz1208** [comment]
@driusan all yours
