### PR TITLE
[dqt] Unable to Load a Saved Query and Other bugs

### LINKED ISSUE #5124: [DQT] Filters - Project menu breaks if one of them has apostrophe in the title
Project drop-down menu in the DQT filters tab is broken when title has apostrophe (see image)

Issue discovered on IBIS --> will be fixed on our end just by renaming the project as wasn't supposed to be named Down's Syndrome but Down Syndrome, so resolved without a fix to DQT for us. However, should change behaviour LORIS-wide to allow apostrophes in case future projects have one in their title.

RM_12492_DQT_Menu_Issue_Reopened_2018-11-07

https://redmine.cbrain.mcgill.ca/issues/15606

### LINKED ISSUE #7935: [DQT] Deleting all filters causes query page to fail
**Describe the bug**
If you define some fields, and on the filter page remove all filters (including the default empty one) and go to the run query page. the run query button is disabled (see screenshots)

Screen Shot 2022-01-04 at 9 58 11 AM
Screen Shot 2022-01-04 at 9 58 04 AM

### LINKED ISSUE #7936: [DQT] Page Error when trying to filter on Select elements
**Describe the bug**
In the DQT when you trying to filter by ~project~ any "enum" field after selecting the demographics category, the project variable, and an operator. the page goes completely blank and an error is thrown 

selection: 
Screen Shot 2022-01-04 at 10 05 54 AM

ERROR:
Screen Shot 2022-01-04 at 10 05 24 AM

### LINKED ISSUE #7939: [DQT] Unable to load a saved query
**Describe the bug**
When saving a query, it seems that everything is going through fine. but the query is not available for loading on the load query page (tested on https://test-loris-dev.loris.ca/dqt)

Environment factors:
- only dataquery_view permission given to user

### PR DESCRIPTION
**Pull request by maltheism**
## Brief summary of changes

Solution for the following bugs:

* Fixes the unable to load a saved query bug. One of the functions needed wasn't being imported in the react.app.js

* Fixes page error when trying to filter on select elements.

* Fixes saving query failure. 

* Fixes Deleting all filters causes query page to fail

* Fixes Filters - Project menu breaks if one of them has apostrophe in the title

#### Testing instructions (if applicable)

1. Checkout PR.
2. make clean && make dev
3. visit DQT module
4. load query

#### Link(s) to related issue(s)

* Resolves #7939
* Resolves #7936
* Resolves #7935
* Resolves #5124

### CODE REVIEW

**Comment by ridz1208** [comment]
@maltheism this is not working for me. I did make cleana nd make dev and here are the changes in the code

```
diff --git a/modules/dqt/jsx/react.app.js b/modules/dqt/jsx/react.app.js
index c209f7d4a..0c8242358 100644
--- a/modules/dqt/jsx/react.app.js
+++ b/modules/dqt/jsx/react.app.js
@@ -16,6 +16,7 @@ import {StepperPanel, ProgressBar} from './components/stepper';
 import SavedQueriesList from './react.savedqueries';
 import ExpansionPanels from './components/expansionpanels';
 import NoticeMessage from './react.notice';
+import {getSessions} from '../js/arrayintersect';
 
 /**
  * DataQueryApp component
@@ -682,7 +683,7 @@ class DataQueryApp extends Component {
       $.ajax({
         url: loris.BaseURL + '/dqt/ajax/datadictionary.php',
         success: (data) => {
-          if (data[0].value.IsFile) {
+          if (data[0] && data[0].value.IsFile) {
             let key = data[0].key[0] + ',' + data[0].key[1];
             let downloadable = this.state.downloadableFields;
             downloadable[key] = true;
```

File: modules/dqt/ajax/saveQuery.php [hunk 1]
```diff
@@ -69,7 +68,7 @@
                                     ': ' .
                                     $_REQUEST['QueryName'];
 }
-$fields = json_decode($_REQUEST['Fields']);
+$fields = json_decode(json_encode($_REQUEST['Fields']));
```
Comment (maltheism) [inline modules/dqt/ajax/saveQuery.php:71]: PHP error here from using json_decode on an array would result in the frontend not getting a valid response and failing the save query for user.

File: modules/dqt/jsx/react.app.js [hunk 2]
```diff
@@ -682,7 +685,7 @@ class DataQueryApp extends Component {
       $.ajax({
         url: loris.BaseURL + '/dqt/ajax/datadictionary.php',
         success: (data) => {
-          if (data[0].value.IsFile) {
+          if (data[0] && data[0].value.IsFile) {
```
Comment (maltheism) [inline modules/dqt/jsx/react.app.js:688]: @ridz1208 this change prevents browser console error when data[0] is undefined

File: modules/dqt/jsx/react.app.js [hunk 3]
```diff
@@ -1151,7 +1154,7 @@ class DataQueryApp extends Component {
    */
   updateFilter(filter) {
     if (filter.children.length === 0) {
-      filter.session = this.state.filter.session;
+      filter.session = this.state.allSessions;
```
Comment (maltheism) [inline modules/dqt/jsx/react.app.js:1157]: @ridz1208 this change is needed for "Deleting all filters causes query page to fail" and this.state.allSessions is a persistent collection of all the sessions that will never be modified. It's needed here in this case when all rules are deleted and the sessions need to be reset back to all sessions.

File: modules/dqt/jsx/react.filterBuilder.js [hunk 4]
```diff
@@ -337,11 +337,10 @@ class FilterRule extends Component {
                   </option>
                 );
               });
-              value = (this.props.rule.value) ? this.props.rule.value : '';
               input = (
                 <select className='input-sm col-xs-3'
                         onChange={this.valueChange}
-                        value={value}>
+                        value={this.props.rule.value ?? ''}>
```
Comment (maltheism) [inline modules/dqt/jsx/react.filterBuilder.js:343]: @ridz1208 this line is a cleanup I noticed before getting to next bug.

File: modules/dqt/jsx/react.tabs.js [hunk 5]
```diff
@@ -184,6 +184,19 @@ class ViewDataTabPane extends Component {
     this.downloadDataCSV = this.downloadDataCSV.bind(this);
   }
 
+  /**
+   * Called by React when the component has updated.
+   * @param {object} prevProps - Previous component properties
+   * @param {object} prevState - Previous component state
+   */
+  componentDidUpdate(prevProps, prevState) {
```
Comment (maltheism) [inline modules/dqt/jsx/react.tabs.js:192]: @ridz1208 this change is part of the solution for the "Fixes page error when trying to filter on select elements" bug. this.state.sessionsLoaded will be set to true once sessions have been retrieved and so if sessions are emptied then the run query button doesn't get reset depending on if fields are selected.

File: modules/dqt/jsx/react.tabs.js [hunk 6]
```diff
@@ -454,9 +467,10 @@ class ViewDataTabPane extends Component {
     ) : null;
 
     let sessionsEmpty = this.props.filter.session.length === 0;
-    if (this.props.AllSessions.length > 0) {
+    if (this.state.sessionsLoaded) {
```
Comment (maltheism) [inline modules/dqt/jsx/react.tabs.js:470]: @ridz1208 this change is part of the solution for the "Fixes page error when trying to filter on select elements" bug. this.state.sessionsLoaded will be set to true once sessions have been retrieved and so if sessions are emptied then the run query button doesn't get reset depending on if fields are selected.

File: modules/dqt/jsx/react.filterBuilder.js [hunk 7]
```diff
@@ -9,7 +9,7 @@
 
 import React, {Component} from 'react';
 import ModalImportCSV from './react.importCSV';
-import {getSessions} from '../js/arrayintersect';
+import {getSessions, enumToArray} from '../js/arrayintersect';
```
Comment (maltheism) [inline modules/dqt/jsx/react.filterBuilder.js:12]: @ridz1208 this import fixes the "Fixes the unable to load a saved query bug. One of the functions needed wasn't being imported in the react.app.js" bug.

File: modules/dqt/jsx/react.app.js [hunk 8]
```diff
@@ -16,6 +16,7 @@ import {StepperPanel, ProgressBar} from './components/stepper';
 import SavedQueriesList from './react.savedqueries';
 import ExpansionPanels from './components/expansionpanels';
 import NoticeMessage from './react.notice';
+import {getSessions} from '../js/arrayintersect';
```
Comment (maltheism) [inline modules/dqt/jsx/react.app.js:19]: @ridz1208 this import fixes the "Fixes the unable to load a saved query bug. One of the functions needed wasn't being imported in the react.app.js" bug.

File: modules/dqt/js/arrayintersect.js [hunk 9]
```diff
@@ -102,12 +102,15 @@ export const getSessions = function(group) {
 };
 
 export const enumToArray = function(enumString) {
-    let tempArray = enumString.split('(')[1].split('\'');
-    let array = [];
-    for (let i = 1; i < tempArray.length; i += 2) {
-        array.push(tempArray[i]);
-    }
-    return array;
+  enumString = enumString.substring('enum('.length); // remove 'enum('
```
Comment (maltheism) [inline modules/dqt/js/arrayintersect.js:105]: @ridz1208 the modified code in this function fixes the "Filters - Project menu breaks if one of them has apostrophe in the title" bug.

**Comment by ridz1208** [comment]
@driusan I asked alizee to fix all the bugs in one PR since they were very difficult to test in isolation. The bugs overlap somewhat and while testing one fix another bug would break the module.

File: tools/CouchDB_Import_Demographics.php [hunk 10]
```diff
@@ -182,66 +182,70 @@ function _generateQuery()
...
-                                s.Current_stage, 
+                                s.Current_stage,
                                 CASE
                                     WHEN s.Visit='Failure' THEN 'Failure'
                                     WHEN s.Screening='Failure' THEN 'Failure'
                                     WHEN s.Visit='Withdrawal' THEN 'Withdrawal'
                                     WHEN s.Screening='Withdrawal' THEN 'Withdrawal'
                                     ELSE 'Neither'
                                 END as Failure,
-                                c.RegistrationProjectID,
```
Comment (maltheism) [inline tools/CouchDB_Import_Demographics.php:199]: @ridz1208 Fixes the DQT Import script not having anything populated for Project

File: tools/CouchDB_Import_Demographics.php [hunk 11]
```diff
@@ -182,66 +182,70 @@ function _generateQuery()
...
-        $tablesToJoin = " FROM session s 
-                            JOIN candidate c USING (CandID) 
-                            LEFT JOIN psc p ON (p.CenterID=s.CenterID) 
-                            LEFT JOIN caveat_options c_o ON (c_o.ID=c.flagged_reason)
-                            LEFT JOIN parameter_candidate AS pc_comment 
-                                ON (pc_comment.CandID=c.CandID) 
+        $tablesToJoin = " FROM session s
+                            JOIN candidate c USING (CandID)
+                            LEFT JOIN psc p ON (p.CenterID=s.CenterID)
+                            LEFT JOIN project pr ON
```
Comment (maltheism) [inline tools/CouchDB_Import_Demographics.php:212]: @ridz1208 Fixes the DQT Import script not having anything populated for Project

File: modules/dqt/js/arrayintersect.js [hunk 12]
```diff
@@ -102,12 +102,15 @@ export const getSessions = function(group) {
...
+  enumString = enumString.slice(0, -1); // remove last ')'
+  const tempArray = enumString.split(', ');
```
[the remark this answers is not in the document]
Comment (maltheism) [reply modules/dqt/js/arrayintersect.js:107]: @ridz1208 no the comma-space is necessary otherwise things will break when multiple commas exist.

File: tools/CouchDB_Import_Demographics.php (hunk 11 above)
Comment (ridz1208) [inline tools/CouchDB_Import_Demographics.php:212]:
```suggestion
                            LEFT JOIN Project pr ON
```

**Review by ridz1208 — CHANGES_REQUESTED** [review]

File: modules/dqt/js/arrayintersect.js (hunk 12 above)
[the remark this answers is not in the document]
Comment (ridz1208) [reply modules/dqt/js/arrayintersect.js:107]: @maltheism what do you mean by when multiple comas exist ? like inside of the enum ?

**Comment by ridz1208** [comment]
@maltheism you reassigned this to me but several of my questions are still unanswered

File: modules/dqt/js/arrayintersect.js (hunk 12 above)
[the remark this answers is not in the document]
Comment (ridz1208) [reply modules/dqt/js/arrayintersect.js:107]: @maltheism 
```suggestion
  const tempArray = enumString.split(/\'( )*,( )*\'/);
```

How it works
Screenshot from 2022-01-11 14-40-41

**Comment by maltheism** [comment]
Hi @ridz1208, I updated the regular expression again.

File: modules/dqt/js/arrayintersect.js [hunk 13]
```diff
@@ -102,12 +102,15 @@ export const getSessions = function(group) {
...
 export const enumToArray = function(enumString) {
-    let tempArray = enumString.split('(')[1].split('\'');
-    let array = [];
-    for (let i = 1; i < tempArray.length; i += 2) {
-        array.push(tempArray[i]);
-    }
-    return array;
+  enumString = enumString.substring('enum('.length); // remove 'enum('
+  enumString = enumString.slice(0, -1); // remove last ')'
+  const tempArray = enumString.split(/,\s*/);
```
Comment (ridz1208) [inline modules/dqt/js/arrayintersect.js:107]: @maltheism thats not the regex I gave you...

This regex:
1. will erroneously match a coma inside one of the values. example `'rida, alizee and dave', 'samir', 'leigh'`
2. will not properly match and remove spaces before comas example `'rida' , 'alizee' , 'dave'`

Comment (maltheism) [reply modules/dqt/js/arrayintersect.js:107]: @ridz1208 the regex you gave me didn't work. I'll take a look at what I can do again.

File: modules/dqt/js/arrayintersect.js [hunk 14]
```diff
@@ -102,12 +102,15 @@ export const getSessions = function(group) {
...
+  let array = [];
+  for (let i = 0; i < tempArray.length; i++) {
+    // remove "'" from beginning and end of string
+    array.push(tempArray[i].substr(1).slice(0, -1));
```
Comment (ridz1208) [inline modules/dqt/js/arrayintersect.js:111]:
```suggestion
  enumString = enumString.substring('enum(\''.length); // remove 'enum('
  enumString = enumString.slice(0, -2); // remove last 2 characters `')`
  const tempArray = enumString.split(/\'\s*,\s*\'/);
  let array = [];
  for (let i = 0; i < tempArray.length; i++) {
    // remove "'" from beginning and end of string
    array.push(tempArray[i]);
```

Comment (ridz1208) [reply modules/dqt/js/arrayintersect.js:111]: tested with 
```
Pumpernickel's stuff
Rye's bread
Challah, and others
DCP
```

File: modules/dqt/ajax/saveQuery.php [hunk 15]
```diff
@@ -81,6 +80,6 @@
     $query['id'] = $qid;
     print json_encode($query);
 } else {
-    print $cdb->postDoc($baseDocument);
+    print json_encode($cdb->postDoc($baseDocument));
```
Comment (ridz1208) [inline modules/dqt/ajax/saveQuery.php:83]:
```
[Wed Jan 19 13:51:34.348020 2022] [php7:error] [pid 52387] [client 127.0.0.1:39804] PHP Fatal error:  Uncaught LorisException: Decoded JSON data returned null. Cannot continue. in /var/www/loris/php/libraries/CouchDB.class.inc:539\nStack trace:\n#0 /var/www/loris/modules/dqt/ajax/saveQuery.php(43): CouchDB->getDoc()\n#1 /var/www/loris/htdocs/AjaxHelper.php(112): require('/var/www/loris/...')\n#2 {main}\n  thrown in /var/www/loris/php/libraries/CouchDB.class.inc on line 539,
```
I get this

Comment (maltheism) [reply modules/dqt/ajax/saveQuery.php:83]: Hi @ridz1208 I'm not getting this error when saving democraphics. Did you do anything special to trigger this bug?

Comment (ridz1208) [reply modules/dqt/ajax/saveQuery.php:83]: @maltheism it seems to be related to spaces in the query name

Comment (maltheism) [reply modules/dqt/ajax/saveQuery.php]: Hi @ridz1208, I fixed that bug with the latest commit.

File: modules/dqt/ajax/saveQuery.php [hunk 16]
```diff
@@ -33,6 +33,9 @@
     $couchConfig['adminpass']
 );
 $qid         = $user->getUserName() . "_" . $_REQUEST['QueryName'];
+if (preg_match('/\s/', $qid)) {
+    $qid = rawurlencode($qid);
+}
```
Comment (ridz1208) [inline modules/dqt/ajax/saveQuery.php:38]: is there a reason not to encode it all the time? why only encode it if there are white spaces ?

File: modules/dqt/ajax/saveQuery.php [hunk 17]
```diff
@@ -34,6 +33,9 @@
...
```
Comment (ridz1208) [inline modules/dqt/ajax/saveQuery.php:38]:
```suggestion
$qid = $user->getUserName() . "_" . $_REQUEST['QueryName'];
$qid = rawurlencode($qid);
```

**Comment by ridz1208** [comment]
@driusan this PR fixes the majority of issues found (and linked to the PR). 1 edge case is not covered:

persistent issue: If you try to save a query choosing a name which contains spaces, and another query with the same name already exists, the UI will display a success bu the old query will not be overridden.

Expected behaviour: The UI should prompt the user to override the previous query or cancel as it does for queries with name which do not contain spaces


I recommend merging the PR and I will create a new issue for this

**Comment by driusan** [comment]
Okay, will do once the tests finish running. I assume the new issue isn't critical?

**Comment by ridz1208** [comment]
@driusan not critical no
