### PR TITLE
[Core] Generically handle uncaught exceptions (no more blank crashes)

### LINKED ISSUE #4368: "Start Next Stage" will crash when instrument does not exist
Error-handling should be improved so that an error message is displayed to the user instead of crashing.

Example stack trace (on `major` branch):
>PHP Fatal error:  Uncaught Exception: Instrument does not exist in /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc:208\nStack trace:\n#0 /var/www/loris/php/libraries/NDB_BVL_Battery.class.inc(195): NDB_BVL_Instrument::factory('tsi', '', '')\n#1 /var/www/loris/php/libraries/NDB_BVL_Battery.class.inc(156): NDB_BVL_Battery->addInstrument('tsi')\n#2 /var/www/loris/modules/next_stage/php/next_stage.class.inc(128): NDB_BVL_Battery->createBattery(2, 'Visit', 'M1', 2, true)\n#3 /var/www/loris/php/libraries/NDB_Form.class.inc(162): LORIS\\next_stage\\Next_Stage->_process(Array)\n#4 /var/www/loris/php/libraries/LorisForm.class.inc(1436): NDB_Form->_save(Array)\n#5 /var/www/loris/php/libraries/NDB_Form.class.inc(133): LorisForm->process(Array)\n#6 /var/www/loris/php/libraries/NDB_Form.class.inc(190): NDB_Form->save()\n#7 /var/www/loris/src/Middleware/UserPageDecorationMiddleware.php(173): NDB_Form->handle(Object(Zend\\Diactoros\\ServerRequest))\n#8 /var/www/loris/src/Middleware/PageDecorationMiddleware.php(49): LORIS\\Middleware\\UserPageDecor in /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc on line 208, referer: https://jsaigle-dev.loris.ca/next_stage/?candID=575139&sessionID=2153&identifier=2153

### PR DESCRIPTION
**Pull request by johnsaigle**
## Brief summary of changes

Modifies the middleware to handle uncaught exceptions in a generic way. **Instead of LORIS crashing and displaying a blank page, it should now display a decorated error template.**

I've also updated the error templates to encourage users to reach out to the project administrator or to report an issue using the issue tracker module.

##### Example of how this fixes #6034 (Uncaught \NotFound exception)

Screen Shot 2020-02-17 at 16 23 20

---

##### Example of how this fixes #4368 (Uncaught Internal Server Error)

Screen Shot 2020-02-17 at 18 00 28

---

#### Testing instructions (if applicable)

1. Test either of the linked issues and make sure that the errors no longer cause crashes.
2. Go to a module that doesn't exist and confirm that LORIS doesn't crash.

#### Related

Fixes #4368

### CODE REVIEW

File: src/Http/Error.php [hunk 1]
```diff
@@ -45,13 +45,30 @@ public function __construct(
...
+        // Admistrator email.
+        $contact  = $factory->config()->getSetting('mail')['From'];
         $tpl_data = array(
                      'message' => $message,
                      'baseurl' => $baseurl,
+                     'contact' => $contact,
                     );
+        // Add issue tracker data if the error is encountered by an authenticated
+        // user with the correct permissions.
+        $user = $factory->user();
```
Comment (xlecours) [inline src/Http/Error.php]:
```suggestion
        $user = $request->getAttribute('user');
```

Comment (johnsaigle) [reply src/Http/Error.php]: good catch, thanks!

**Comment by johnsaigle** [comment]
@driusan Could you provide a bit more detail? I'd like to implement this but I don't really know my way around the architecture well enough to know where else this code should go.

**Comment by driusan** [comment]
Middleware are things which implement a `process` function to modify a request before passing it to a handler or modifying a response that comes back from a handler. See PSR-15 for the interface.

``
/**
 * A ResponseGenerator is a type of MiddlewareChainer which terminates the
 * chain and forces a response to be returned unconditionally.
 *
```

You are attempting to do make it to something completely unrelated to the `ResponseGenerator`'s job. You're trying to modify the response by catching exceptions and displaying an error page. You should do that by creating a new middleware (like `ExceptionCatchingMiddleware` or something) in `src/Middleware` that is only concerned with catching exceptions.

**Comment by johnsaigle** [comment]
Thanks for explaining. I've added a new class containing the code I previously added to ResponseGenerator.

This still needs work because I need to figure out exactly where in the chain of middleware that this new one should go. I'm thinking the BaseRouter right now since I think we want this middleware to be as upstream as possible so we have a better chance of catching stray exceptions.

**Comment by johnsaigle** [comment]
@driusan This new approach is working for me locally so it's ready for your review.

File: src/Middleware/ExceptionHandlingMiddleware.php [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+    }
+
+    /**
+     * Implements the MiddlewareChainer interface
+     *
+     * @param MiddlewareChainer $next The next middleware to chain. (Discarded)
+     *
+     * @return MiddlewareChainer The same MiddlewareChainer, unmodified.
+     */
+    public function withMiddleware(MiddlewareChainer $next)
```
Comment (driusan) [inline src/Middleware/ExceptionHandlingMiddleware.php]: This shouldn't be discarding next. It should be chaining with it. You can use the `MiddlewareChainerMixin` (see ContentLengthMiddleware)

File: src/Middleware/ExceptionHandlingMiddleware.php [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+     *                                         valid requests to
+     *
+     * @return ResponseInterface the PSR15 response.
+     */
+    public function process(
+        ServerRequestInterface $request,
+        RequestHandlerInterface $handler
+    ) : ResponseInterface {
+        try {
+            return (new \LORIS\Middleware\ResponseGenerator())
```
Comment (driusan) [inline src/Middleware/ExceptionHandlingMiddleware.php]: This shouldn't be calling the ResponseGenerator, it should be chaining to the next middleware in the chain. See ContengLengthMiddleware for an example.

File: src/Middleware/ExceptionHandlingMiddleware.php [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+                ->process(
+                    $request,
+                    $handler
+                );
+        } catch (\Exception $e) {
+            // Handle uncaught errors.
+            switch (get_class($e)) {
```
Comment (driusan) [inline src/Middleware/ExceptionHandlingMiddleware.php]: Why is this not 2 catch statements to catch different types of exceptions?

File: htdocs/index.php [hunk 5]
```diff
@@ -30,7 +30,7 @@
 // any authentication middleware, because that's done dynamically
 // based on the module router, depending on if the module is public.
 $middlewarechain = (new \LORIS\Middleware\ContentLength())
-    ->withMiddleware(new \LORIS\Middleware\ResponseGenerator());
+    ->withMiddleware(new \LORIS\Middleware\ExceptionHandlingMiddleware());
```
Comment (driusan) [inline htdocs/index.php]: The ResponseGenerator shouldn't be removed from the chain

File: src/Middleware/ExceptionHandlingMiddleware.php (hunk 4 above)
Comment (johnsaigle) [reply src/Middleware/ExceptionHandlingMiddleware.php]: This seemed more concise

**Comment by johnsaigle** [comment]
@driusan Thanks for the feedback. how's this?

File: htdocs/index.php [hunk 6]
```diff
@@ -29,7 +29,8 @@
 // Middleware that happens on every request. This doesn't include
 // any authentication middleware, because that's done dynamically
 // based on the module router, depending on if the module is public.
-$middlewarechain = (new \LORIS\Middleware\ContentLength())
+$middlewarechain = (new \LORIS\Middleware\ExceptionHandlingMiddleware())
+    ->withMiddleware(new \LORIS\Middleware\ContentLength())
```
Comment (driusan) [inline htdocs/index.php]: Are you sure these are the right order? I can't remember if the chain is a stack or a queue, but can you make sure this calculates the content-length of the error page, and not of the pre-modified data?

Comment (johnsaigle) [reply htdocs/index.php]: > 1.4 Handling Exceptions
It is RECOMMENDED that any application using middleware includes a component that catches exceptions and converts them into responses. **This middleware SHOULD be the first component executed and wrap all further processing to ensure that a response is always generated.**

https://www.php-fig.org/psr/psr-15/

If that's any consolation

Comment (johnsaigle) [reply htdocs/index.php]: Inverting the order doesn't seem to change the Content-Length value for the 500 response error page (see screenshot in OP). I made sure to refresh with Cmd + Shift + R to clear the cache

Comment (driusan) [reply htdocs/index.php]: I don't see the network dev console/http response headers in the screenshot, how can I check the Content-Length value?

Comment (johnsaigle) [reply htdocs/index.php]: I just meant that was the page I was testing, not that the content-length is there.

They match in manual testing for me. Maybe you can confirm locally to verify?

**Comment by johnsaigle** [comment]
@ridz1208 @driusan I'd recommend that this PR goes into the release as it's a pretty simple change that adds huge utility by 1) preventing crashes in LORIS and 2) providing debug messages by handling uncaught exceptions. I expect that it should reduce our maintenance overhead when users encounter bugs.

**Comment by driusan** [comment]
This emphatically does *not* prevent crashes in LORIS. It makes error pages prettier when things crash at the trade off of hiding the debugging information of uncaught exceptions. I don't think it merits an exception to the release freeze.

**Comment by johnsaigle** [comment]
OK. Should I amend the pull request to also log the caught exceptions? That was it's only an improvement, not a trade-off.

File: src/Middleware/ExceptionHandlingMiddleware.php [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+            error_log($e->getMessage() . $e->getTraceAsString());
+            $status = 404;
+        } catch (\Exception $e) {
+            error_log($e->getMessage() . $e->getTraceAsString());
+            $status = 500;
+        }
+
+        // Decorate the request.
+        return (new \LORIS\Middleware\PageDecorationMiddleware(
+            \NDB_Factory::singleton()->user()
```
Comment (driusan) [inline src/Middleware/ExceptionHandlingMiddleware.php:47]: This should be coming from the request object 'user' attribute which is populated by the BaseRouter.

File: src/Http/Error.php [hunk 8]
```diff
@@ -45,13 +45,30 @@ public function __construct(
         string $message = ''
     ) {
 
+        $factory = \NDB_Factory::singleton();
```
Comment (driusan) [inline src/Http/Error.php:48]: No other response type is using globals, you can just pass the parameters you want in as function arguments.

**Comment by johnsaigle** [comment]
@driusan I reworked this to use request attributes instead of globals. Can you take another look?

File: src/Http/Error.php [hunk 9]
```diff
@@ -45,13 +45,33 @@ public function __construct(
...
```
Comment (driusan) [inline src/Http/Error.php:48]: This isn't being used now

File: src/Http/Error.php [hunk 10]
```diff
@@ -45,13 +45,33 @@ public function __construct(
...
+
         $uri     = $request->getURI();
         $baseurl = $uri->getScheme() .'://'. $uri->getAuthority();
-
+        // Admistrator email.
+        $contact  = $request
+            ->getAttribute('loris')
+            ->getConfiguration()
+            ->getSetting('mail')['From'];
```
Comment (driusan) [inline src/Http/Error.php:56]: why don't you just pass in the administrator email and the user object directly?

File: src/Http/Error.php [hunk 11]
```diff
@@ -45,13 +45,33 @@ public function __construct(
...
         $tpl_data = array(
                      'message' => $message,
                      'baseurl' => $baseurl,
+                     'contact' => $contact,
                     );
+        // Add issue tracker data if the error is encountered by an authenticated
+        // user with the correct permissions.
+        $user = $request->getAttribute('user');
+        if (! $user instanceof \LORIS\AnonymousUser) {
```
Comment (driusan) [inline src/Http/Error.php:65]: This if logic here is wrong. canReport should be based on hasAnyPermission regardless of the type of user (AnonymousUsers won't have the permission, and if LORIS is intentionally set up so that they do it shouldn't be bypassed.), and issueTrackerURL should be based on whether canReport is true.

File: src/Http/Error.php (hunk 10 above)
Comment (johnsaigle) [reply src/Http/Error.php:56]: Wouldn't that require updating all of the calling code?

File: src/Http/Error.php (hunk 11 above)
Comment (johnsaigle) [reply src/Http/Error.php:65]: OK I can remove the if statement.

I'm not really sure what you mean by "issueTrackerURL should be based on whether canReport is true."

File: src/Http/Error.php (hunk 9 above)
Comment (johnsaigle) [inline src/Http/Error.php:48]:
```suggestion
```

File: src/Http/Error.php (hunk 10 above)
Comment (driusan) [reply src/Http/Error.php:55]: I didn't realize $request was already being passed, I thought you added it for this and were changing it anyways.. nevermind, since it's already there you can use it directly

File: src/Http/Error.php (hunk 11 above)
Comment (driusan) [reply src/Http/Error.php:64]: The other template variable conditionally being set in the if statement

```
  $tpl_data['issueTrackerURL'] = '/issue_tracker/issue/new';
```

The condition for that being set should be `if ($canReport === true)`, not `if (! $user instanceof \LORIS\AnonymousUser)`.. though it also doesn't matter if you just unconditionally set it, since the template won't use it if it doesn't need it.

File: src/Http/Error.php [hunk 12]
```diff
@@ -44,14 +44,42 @@ public function __construct(
...
-                    );
+        $tpl_data = [];
+
+        $lorisInstance = $request->getAttribute('loris');
+        $user          = $request->getAttribute('user') ?? new \LORIS\AnonymousUser();
+        
+
+        // Add a link to the issue tracker as long as a LORIS Instance object
+        // is present in the request.
+        if (! $user instanceof \LORIS\AnonymousUser
```
Comment (driusan) [inline src/Http/Error.php:58]: Why is this check re-added?

Comment (johnsaigle) [reply src/Http/Error.php:58]: I removed it but it caused a bunch of errors, e.g. relating to calling `hasPermission()` on `null` farther down the stack. Removing it seems to break everything

File: src/Middleware/ExceptionHandlingMiddleware.php (hunk 7 above)
Comment (driusan) [reply src/Middleware/ExceptionHandlingMiddleware.php:47]: This is still not done.

Comment (johnsaigle) [reply src/Middleware/ExceptionHandlingMiddleware.php:47]: I think this had similar issues to the Anonymous User call above. When I changed it there were cases where the 'user' attribute was null.

Comment (johnsaigle) [reply src/Middleware/ExceptionHandlingMiddleware.php:47]: @driusan Can you follow up on this point and the above point?

Comment (johnsaigle) [reply src/Middleware/ExceptionHandlingMiddleware.php:47]: @driusan bump

Comment (driusan) [reply src/Middleware/ExceptionHandlingMiddleware.php:47]: There should never be cases where it's null, it's added unconditionally from the BaseRouter

Comment (johnsaigle) [reply src/Middleware/ExceptionHandlingMiddleware.php:47]: I just tested again. It works as long as the Anonymous User check is there. Otherwise this error occurs when a user is not logged in:

Uncaught TypeError: Argument 1 passed to LORIS\\Middleware\\PageDecorationMiddleware::__construct() must be an instance of User, null given, called in /var/www/loris/src/Middleware/ExceptionHandlingMiddleware.php on line 47 and defined in /var/www/loris/src/Middleware/PageDecorationMiddleware.php:18

File: src/Http/Error.php (hunk 12 above)
Comment (johnsaigle) [reply src/Http/Error.php:58]: Without this check, this error occurs for unathenticated users:

Uncaught TypeError: Argument 1 passed to LORIS\\Middleware\\PageDecorationMiddleware::__construct() must be an instance of User, null given, called in /var/www/loris/src/Middleware/ExceptionHandlingMiddleware.php on line 47 and defined in /var/www/loris/src/Middleware/PageDecorationMiddleware.php:18
