### PR TITLE
[publication] Give publication creator edit permissions

### LINKED ISSUE #7401: [publication] Edit Permissions not assigned to creator of proposal
**Describe the bug**
When a publication proposal is submitted, the user creating the issue should be able to go back and edit the form. This is currently not the case. I believe the permission for the creator is never inserted into `publication_users_edit_perm_rel`

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `Publication`
2. Create & submit a project proposal
3. Try accessing the created proposal and notice that you cannot edit the fields (other than status)

**What did you expect to happen?**
To be able to edit the form.

### PR DESCRIPTION
**Pull request by jesscall**
## Brief summary of changes
This PR ensures that the creator of a publication project is added to the `publication_users_edit_perm_rel` table and given edit access to their submission.

#### Testing instructions (if applicable)
1. Before checking out this PR, go to `Publication`
2. Create & submit a project proposal
3. Try accessing the created proposal and notice that you cannot edit the fields (other than status)
4. Checkout this PR
5. Repeat steps 1-3 and make sure that this time you can edit the fields

#### Link(s) to related issue(s)

* Resolves #7401

### CODE REVIEW

File: modules/publication/ajax/FileUpload.php [hunk 1]
```diff
@@ -100,6 +100,15 @@ function uploadPublication() : void
...
 
+    // give creator permission to edit
+    $db->insert(
+        'publication_users_edit_perm_rel',
+        [
+            'PublicationID' => $pubID,
+            'UserID'        => $uid,
+        ]
+    );
+
```
Comment (pierre-p-s) [inline modules/publication/ajax/FileUpload.php:111]: I think admin should always be added to users with edit permissions

```suggestion
    $db->insert(
        'publication_users_edit_perm_rel',
        [
            'PublicationID' => $pubID,
            'UserID'        => $uid,
        ]
    );


    $db->insert(
        'publication_users_edit_perm_rel',
        [
            'PublicationID' => $pubID,
            'UserID'        => 'admin',
        ]
    );
```

Comment (jesscall) [reply modules/publication/ajax/FileUpload.php:111]: `admin` is only a CCNA username. Other projects may have different names. For example I believe raisinbread uses `lorisadmin`. Also `admin` is not the `userID`.

Should I just add `userID => 1`? Is this good practice ? @ridz1208

Comment (ridz1208) [reply modules/publication/ajax/FileUpload.php:111]: correct, but also, we don't really want to automatically assign admin permissions in that way. If the goal is to give admin access to everything then this should be handled where you check for the permissions not where you assign the permissions (and even at that I don't think admin should be able to have access and edit everything).

**Review by ridz1208 — APPROVED** [review]

**Comment by ridz1208** [comment]
@pierre-p-s can you confirm manual tests pass ?

**Comment by pierre-p-s** [comment]
> @pierre-p-s can you confirm manual tests pass ?

Yes it passed manual test

**Review by pierre-p-s — APPROVED** [review]
