### PR TITLE
[New Profile] Fix issue where candidate creation failed. Also, update phpstan + fix errors

### LINKED ISSUE #6059: [CORE] Can't generate a new candidate
**Describe the bug**
get `Uncaught DomainException: Values not configured properly for PSCIDGenerator. Please correct your configuration file.Length: `4`\nAlphabet: `0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ`\nMin: ``\nMax: `9999`\nLength: `CHA`\nGeneration: `sequential`\n in `

error reported on PSCID generation.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'Candidate -> new profile'
2. Set the proper values for the new candidate
3. Click on `Create`
4. button `gray-out` and nothing append, error in the log

**What did you expect to happen?**
A new candidate to be created and page update with candidate's profile

**Server Environment (if known):**
- LORIS Version: [aces/master, last commit at time]
- Linux distribution and Version: [e.g. Ubuntu 16.04]
- MySQL/MariaDB Version: [e.g. MySQL 5.7]

**Additional context**
ran `checkout aces/master`, `make` and `php raisinbread_refresh.php`

config.xml file with proper value as indicated on docs/config/config.xml
```
   <!-- study variables -->
    <study>
        <PSCID>
            <!-- PSCID (Study Center ID) generation method possible options: sequential/random/user -->
            <generation>sequential</generation>
            <structure>
                <seq type="projectAbbrev"/>
                <seq type="alphanumeric" length="4" min='1' max='9999'/>  <!-- Ex: AAA1-->
            </structure>
        </PSCID>

        <ExternalID>
            <generation>random</generation>
            <structure>
                <seq type="static">BBB</seq>
                <seq type="numeric" length="4" min='1000' max='9999'/>
            </structure>
        </ExternalID>
```

### PR DESCRIPTION
**Pull request by johnsaigle**
## Brief summary of changes

Updates phpstan to the latest version.

SiteIDGenerator had to undergo refactoring to satisfy phpstan's strict type checks but should function the same as before.

By chance this also fixes #6059

### CODE REVIEW

**Comment by johnsaigle** [comment]
```
modules/statistics/php/stats_behavioural.class.inc:157 PhanTypeMismatchDimFetch When fetching an array index from a value of type string, found an array index of type 'total', but expected the index to be of type int
modules/statistics/php/stats_behavioural.class.inc:223 PhanTypeMismatchDimFetch When fetching an array index from a value of type string, found an array index of type 'total', but expected the index to be of type int
```

Basically phan thinks that these lines in the stats module is being accessed with the wrong type of key. For some reason it thinks that there should be an `int` type key but it's actually a string.

The array it has an issue with is a **reference** to`&$tpl_data`, so I don't think there's any place where I can type hint this to make it more clear for Phan. 

I'm not sure how to fix this.

File: php/libraries/CandIDGenerator.php [hunk 1]
```diff
@@ -26,11 +26,11 @@
 class CandIDGenerator extends IdentifierGenerator
 {
     /**
-     * CandIDs should always be exactly 6 digits.
+     * CandIDs should always be exactly 6 integers.
```
Comment (PapillonMcGill) [inline php/libraries/CandIDGenerator.php]: I prefer `6 digits`. Or at least `6 digits integer value`

File: php/libraries/SiteIDGenerator.php [hunk 2]
```diff
@@ -233,19 +221,19 @@ private function _getIDSetting(
                 );
             }
         }
-        // Min, max, and length values should be returned as integers or as
+        // The remaining valeues - min, max, and length - should be returned as
```
Comment (PapillonMcGill) [inline php/libraries/SiteIDGenerator.php]:
```suggestion
        // The remaining values - min, max, and length - should be returned as
```

File: php/libraries/IdentifierGenerator.php [hunk 3]
```diff
@@ -28,13 +28,59 @@ abstract class IdentifierGenerator
...
+    /**
+     * How the ID will be generated. 'sequential' or 'random'.
+     *
+     * @var string
+     */
     protected $generationMethod;
+    /**
+     * An array of all the valid characters that can be used in the ID.
+     *
+     * @var array<int,float|int> This is derived from the return type of PHP's
```
Comment (PapillonMcGill) [inline php/libraries/IdentifierGenerator.php]: Are you sure `$alphabet` will either contain int or float values? I would have guest `char` would be more likely

Comment (johnsaigle) [reply php/libraries/IdentifierGenerator.php]: I'll look into it. It's possible that PHP stores this internally as ASCII because i remember phpstan giving an error about this.

**Comment by johnsaigle** [comment]
Marking this with Priority High since without it new candidates can't be created. #6059

**Comment by johnsaigle** [comment]
@PapillonMcGill I updated the function document. Can you update your review?

**Comment by johnsaigle** [comment]
@driusan Can you review?

File: php/libraries/IdentifierGenerator.php [hunk 4]
```diff
@@ -67,21 +113,6 @@ protected function createNewID(): string
...
-        if (empty($this->siteAlias) && empty($this->projectAlias)) {
-            throw new \InvalidArgumentException(
-                'Either siteAlias or projectAlias must not be empty'
-            );
-        }
-        // Assign class property 'prefix' to whichever alias is not empty.
-        !empty($this->siteAlias) ?
-            $this->prefix   = $this->siteAlias
-            : $this->prefix = $this->projectAlias;
-
```
Comment (driusan) [inline php/libraries/IdentifierGenerator.php]: Removing this checkig looks like a regression. Why is it deleted?

File: php/libraries/UserPermissions.class.inc [hunk 5]
```diff
@@ -90,11 +90,7 @@ class UserPermissions
         // Fill the permissions array of this UserPermissions object with the
         // values extracted for this user from the database.
         if (is_array($results) and !empty($results)) {
-            foreach ($results AS $row) {
-                if (empty($row['userID'])) {
-                    $this->permissions[$row['code']] = false;
-                    continue;
-                }
```
Comment (driusan) [inline php/libraries/UserPermissions.class.inc]: This also appears to be a regression

File: php/libraries/IdentifierGenerator.php (hunk 4 above)
Comment (johnsaigle) [reply php/libraries/IdentifierGenerator.php]: This check was actually causing a bug reported in the linked issued. 

This validation is now done in the child class SiteIDGenerator instead. It's more appropriate here because only PSCIDs and ExternalIDs need Site/Project aliases for their prefix. By contrast, CandIDGenerator extends IdentifierGenerator but doesn't use this functionality at all.

File: php/libraries/UserPermissions.class.inc (hunk 5 above)
Comment (johnsaigle) [reply php/libraries/UserPermissions.class.inc]: iirc I removed this because it's redundant. `$row['userID']` can be 0 which would trigger the empty check. But in that case, Line 94 will always be false because `$this->userID` is taken from the ID of the `users` table which will never be 0. If line 94 is false, then the `$this->permissions` array will be correctly set to be false for that permission code.

Comment (driusan) [reply php/libraries/UserPermissions.class.inc]: This is intended to unset any permissions which were unchecked on the request, it has nothing to do with userID 0 (which as far as I know should never exist)

Comment (johnsaigle) [reply php/libraries/UserPermissions.class.inc]: That's what I'm saying, I think line 94 and 95 (in the new code) are logically equivalent to what I deleted. These two lines alone will unset the permissions.

Comment (johnsaigle) [reply php/libraries/UserPermissions.class.inc]: Just to be clear I meant 94 and 95 on the right-hand side, not in the deleted code.
