### PR TITLE
[api] Fix value in "Sex" field of candidate API

### LINKED ISSUE #6951: [candidate dashboard] Unable to access any candidate dashboard
**Describe the bug**
When trying to access the candidate dashboard via `New Access Profile (Beta)`, I am unable to access any candidate's information.

Screen Shot 2020-09-02 at 13 49 44

This was found while trying to test the widgets for the Media module.

### LINKED ISSUE #6995: [New Access profile] Blank page displayed for all candidates
**Describe the bug**
Every time I access the new `Access Profile` for a candidate, a blank page is displayed. Seems to occur for every candidate.

### LINKED ISSUE #7008: [candidate_profile] ReactJS issue.
**Describe the bug**
A ReactJS issue is preventing the candidate profile to be shown.

**To Reproduce**
1. Log into the system with a user with enough privileges to see the candidate profile.
2. Go to the URL and try to request a candidate profile for wich the current logged user have access to (example: `IP/candidate_profile/300001`) been `300001 a DCCID` of a candidate the current user have access to.
3. See error on the console
image

**What did you expect to happen?**
The system to show the requested candidate profile.

### PR DESCRIPTION
**Pull request by driusan**
The "Sex" attribute in the single candidate portion of the API
was incorrectly being serialized as an object with a "value" key instead
of a string.

This fixes it by implementing to JSONSerializable interface to
serialize Sex objects as strings.

Fixes #6951
Fixes #6995
Fixes #7008

### CODE REVIEW

**Comment by driusan** [comment]
@racostas @nicolasbrossard @HenriRabalais can you confirm that this PR resolves your bugs linked above?

File: src/StudyEntities/Candidate/Sex.php [hunk 1]
```diff
@@ -23,7 +23,7 @@
  * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
  * @link     https://www.github.com/aces/Loris/
  */
-class Sex
+class Sex implements \JsonSerializable
 {
     /* @var string */
     public $value;
```
Comment (maltheism) [inline src/StudyEntities/Candidate/Sex.php:29]: Should this be private?

**Review by maltheism — CHANGES_REQUESTED** [review]

File: src/StudyEntities/Candidate/Sex.php (hunk 1 above)
Comment (driusan) [reply src/StudyEntities/Candidate/Sex.php:29]: Maybe `protected`? Regardless I don't want to change something unrelated in this PR and risk introducing new bugs.

**Review by maltheism — APPROVED** [review]

**Comment by HenriRabalais** [comment]
This fixes my issue!

**Comment by nicolasbrossard** [comment]
@driusan Pulled your branch and the new access profile page now displays properly.

**Comment by driusan** [comment]
2 for 3, I'll just assume the third is fixed as well and merge..
