### PR TITLE
[API] Fix PUT request for Candidates \visit endpoint and integration test

### LINKED ISSUE #7106: The PUT request allows to edit a candidate from a Site where the User has no affiliation with (but should not)
**Describe the bug**
The PUT request should never allow to edit a candidate from a Site where the User has no affiliation with. In this case, the test User has only affiliation with Data Coordinating Center. It is however possible to do so if the new Site is Data Coordinating Center.

For example, in raisinbread, candidate 300001 (https://.loris.ca/api/v0.0.3/candidates/300001) is from site Montreal. The test user should not be able to modify this candidate, because he/she is from Montreal, but is able to.

**To Reproduce**
1. Go to `https://<hostname>/api/v0.0.4-dev/candidates/300001/V3`. 
2. Make sure the User that will be used don't have affiliation with Montreal (or the site the candidate 300001 is affiliated with if different than Montreal).
3. Get the API token using: curl https://<hostname>/api/v0.0.4-dev/login -d '{"username": "<username>", "password": "<password>"}'
4. Store the long string it returns in a variable (`e.g. $token`)
5. In the terminal, enter curl -X PUT -H "Authorization: Bearer $token" https://<hostname>/api/v0.0.4-dev/candidates/300001/V3 -d '{"CandID":"300001","Visit":"V3","Site":"Data Coordinating Center","Battery":"Stale","Project":"Pumpernickel"}'
6. Return to https://.loris.ca/api/v0.0.3/candidates/300001 ; it should be changed to Data Coordinating Center (though it is not what should happen)

**What did you expect to happen?**
The user should be forbidden to change that visit. It should return an error message (`HTTP error 403`).

### PR DESCRIPTION
**Pull request by spell00**
## Brief summary of changes

The PUT request should never allow to edit a candidate from a `Site `where the User has no affiliation with. In this case, the test User has only affiliation with Data Coordinating Center (DCC). It is however possible to do so if the new `Site` is DCC.

For example, in raisinbread, candidate 300001 (`https://<hostname>.loris.ca/api/v0.0.4-dev/candidates/300001`) is from site `Montreal`. The test user should not be able to modify this candidate, because the candidate is from Montreal, but is able to.

Also adds automatic the integration tests to test the changes suggested.

#### Testing instructions

The testing is made automatic.

To test manually: 

1. Before the test, make sure the User that will be used don't have affiliation with Montreal.

2. First get the API token using: `curl https://<hostname>/api/v0.0.3/login -d '{"username": "<username>", "password": "<password>"}'`

3. In the terminal, enter `curl -X PUT -H "Authorization: Bearer $token" https://<hostname>/api/v0.0.4-dev/candidates/300001/V3 -d '{"CandID":"300001","Visit":"V3","Site":"Montreal","Battery":"Low Yeast","Project":"Pumpernickel"}'`

#### Link(s) to related issue(s)

* Resolves #7106

### CODE REVIEW

File: raisinbread/test/api/LorisApiVisitsTest.php [hunk 1]
```diff
@@ -114,7 +114,162 @@ public function testGetCandidatesCandidVisit(): void
...
+                'http_errors' => false
+            ]
+        );
+        // Verify the status code
+        $this->assertEquals(403, $response->getStatusCode());
+        // Verify the endpoint has a body
+        $body = $response->getBody();
+        $this->assertNotEmpty($body);
+
+        $json     = ['CandID'  => "115788",
```
Comment (xlecours) [inline raisinbread/test/api/LorisApiVisitsTest.php:165]: Could you add a comment about this third test?

File: raisinbread/test/api/LorisApiVisitsTest.php [hunk 2]
```diff
@@ -114,7 +114,162 @@ public function testGetCandidatesCandidVisit(): void
...
+                'http_errors' => false
+            ]
+        );
+        // verify the status code
+        $this->assertequals(409, $response->getstatuscode());
+        // verify the endpoint has a body
+        $body = $response->getbody();
+        $this->assertnotempty($body);
+
+        // Test assigning site with no affiliation
```
Comment (xlecours) [inline raisinbread/test/api/LorisApiVisitsTest.php:186]: What is the difference between this test and the second one? Could you explain in a comment?

**Review by xlecours — CHANGES_REQUESTED** [review]

File: raisinbread/test/api/LorisApiVisitsTest.php (hunk 1 above)
Comment (spell00) [reply raisinbread/test/api/LorisApiVisitsTest.php:166]: done.

File: raisinbread/test/api/LorisApiVisitsTest.php (hunk 2 above)
Comment (spell00) [reply raisinbread/test/api/LorisApiVisitsTest.php]: I tried to give more details in the comment of this test. The second test asserts that a visit can't be modified from a site without affiliation to a site with affiliation (Rome -> DCC). This one asserts that a visit can't be modified from a site without affiliation to a site with affiliation to a site without affiliation (DCC -> Montreal).

**Review by xlecours — APPROVED** [review]

**Comment by christinerogers** [comment]
@driusan requesting final review - this is our last stretch in which @spell00 can readily make changes.  thank you!

**Comment by spell00** [comment]
blocked by #7101

**Comment by spell00** [comment]
@xlecours @driusan It is passing Travis checks now and is ready for final review

File: modules/api/php/endpoints/candidate/visit/visit.class.inc [hunk 3]
```diff
@@ -215,11 +215,19 @@ class Visit extends Endpoint implements \LORIS\Middleware\ETagCalculator
             $this->_candidate->getListOfVisitLabels()
         );
 
+        if (!in_array($this->_candidate->getCenterID(), $user->getCenterIDs())) {
```
Comment (driusan) [inline modules/api/php/endpoints/candidate/visit/visit.class.inc:218]: The `Candidate` class implements the `AccessibleResource` interface. I think this should just be using`$this->_candidate->isAccessibeBy($user)` instead of duplicating the logic in slightly different ways in the API. (That would also handle Project permissions, which this is currently not doing.)

**Comment by spell00** [comment]
@driusan I did the correction, this is ready for re-review

File: modules/api/php/endpoints/candidate/visit/visit.class.inc [hunk 4]
```diff
@@ -215,11 +215,18 @@ class Visit extends Endpoint implements \LORIS\Middleware\ETagCalculator
             $this->_candidate->getListOfVisitLabels()
         );
 
+        if (!$this->_candidate->isAccessibleBy($user)) {
+            return new \LORIS\Http\Response\JSON\Forbidden(
+                'You can`t create or modify that candidate'
```
Comment (driusan) [inline modules/api/php/endpoints/candidate/visit/visit.class.inc:220]:
```suggestion
                "You can't create or modify that candidate"
```

"can't" doesn't have a backtick in it.

File: modules/api/php/endpoints/candidate/visit/visit.class.inc [hunk 5]
```diff
@@ -215,11 +215,18 @@ class Visit extends Endpoint implements \LORIS\Middleware\ETagCalculator
...
+            );
+        }
+
         $centerid = array_search($visitinfo['Site'], \Utility::getSiteList());
 
         if (!in_array($centerid, $user->getCenterIDs())) {
             return new \LORIS\Http\Response\JSON\Forbidden(
-                'You can`t create candidates visit for that site'
+                'You can`t create  or modify candidates visit for the site ' .
```
Comment (driusan) [inline modules/api/php/endpoints/candidate/visit/visit.class.inc:228]:
```suggestion
                "You can't create  or modify candidates visit for the site " .
```

**Comment by spell00** [comment]
@driusan I fixed the backticks

File: modules/api/php/endpoints/candidate/visit/visit.class.inc (hunk 5 above)
Comment (spell00) [reply modules/api/php/endpoints/candidate/visit/visit.class.inc]: I changed it

File: modules/api/php/endpoints/candidate/visit/visit.class.inc (hunk 4 above)
Comment (spell00) [reply modules/api/php/endpoints/candidate/visit/visit.class.inc]: I changed it

File: modules/api/php/endpoints/candidate/visit/visit.class.inc (hunk 3 above)
Comment (spell00) [reply modules/api/php/endpoints/candidate/visit/visit.class.inc]: It is now using $this->_candidate->isAccessibleBy($user)

**Review by driusan — APPROVED** [review]
pending Travis

**Comment by spell00** [comment]
@driusan It passed Travis
