### PR TITLE
[Raisinbread] Fixing help_editor module to display RB instrument instructions

### LINKED ISSUE #5691: [Raisinbread] No data for help editor module?
It doesn't seem to be possible to edit any help files using the Raisinbread dataset. The Test VM, demo, and my sandbox contain no data.

How is this module being tested?

### PR DESCRIPTION
**Pull request by AlexandraLivadas**
**Edited** 
This PR aimed to add data to the `help` table in Raisinbread so that the data would generate in the Help Editor module. This will allow the `Help Editor` module to be manually tested.

It was found that there is a bug in this module that causes it not to save/display this information. This issue is resolved in this PR. 

Here is a screenshot of the `Help Editor` module with the new data:
Screen Shot 2020-08-12 at 6 11 24 PM

#### Testing instructions (if applicable)
With a fresh RB install:
1. Navigate to `Help Editor` in the frontend and see that data loads for instructions for the BMI instrument.

#### Link to related issue

* Resolves #5691

### CODE REVIEW

**Comment by christinerogers** [comment]
great, can you also comment in one line on whether the help editor seems to work in terms of editing help text?

**Comment by AlexandraLivadas** [comment]
After testing with the data added, the Help Editor does not correctly save changes made in the frontend to the file contents. I made changes to the contents and hit `Save`. The changes displayed correctly but once I hit `Return to Help Editor` or navigated back to the main page myself, the changes were actually not saved.

Another issue is that the button `Return to Help Editor` does not actually return me to the main Help Editor page. Instead, I stayed on the editing content page and the changes I made were not saved.

File: raisinbread/RB_files/RB_help.sql [hunk 1]
```diff
@@ -1,5 +1,6 @@
 SET FOREIGN_KEY_CHECKS=0;
 TRUNCATE TABLE `help`;
 LOCK TABLES `help` WRITE;
+INSERT INTO `help` (`helpID`, `parentID`, `hash`, `topic`, `content`, `created`, `updated`) VALUES (123,12,'hash','BMI Instructions','The BMI calculator instrument can calculate the BMI and BMI Classification of a visitor. The two required fields for this instrument are the Date of Administration of the instrument and the Examiner name. The height and weight of the visitor must then be entered in either standard or metric units. The instrument will not accept an entry where the height and weight are given in both units. After this information is given, the instrument will calculate the BMI and BMI Classification of the visitor.',NULL,NULL);
```
Comment (christinerogers) [inline raisinbread/RB_files/RB_help.sql:4]: Alex, since this doesn't actually render for the BMI -- [ per your comment here ](https://github.com/aces/Loris/issues/6906#issuecomment-674946742)
I think it might not be because of the value in the `topic` column.  if you change it to `bmi` which i think would be the relevant test_name value for this instrument -- what happens? 

Could you also take another step here towards resolving it by checking the code and to see how the Help display/dropdown actually trying to locate relevant help text?  If it's not trying to match the `topic` column against a valid `test_name` value -- then what is it trying to look for?

Comment (AlexandraLivadas) [reply raisinbread/RB_files/RB_help.sql:4]: Yes I can definitely look into this :)

Comment (AlexandraLivadas) [reply raisinbread/RB_files/RB_help.sql:4]: @christinerogers @driusan  So after some digging:
The help file is handled by [helpHandler.js](https://github.com/aces/Loris/blob/main/htdocs/js/helpHandler.js). This then calls the [modules/help_editor/ajax/help.php](https://github.com/aces/Loris/blob/main/modules/help_editor/ajax/help.php) file with a GET request.
 
In THAT file, it first tries to render the help file by either using the module name (which is given by the request parameter `testName` or using the `subtest` parameter (in this case "bmi" or "aosi"). If it's not a module, it instead tries to load data from the `help` table using the request parameter `subtest` as the identifier. But when I went to an instrument data entry page and used the Developer Tool, I saw that when the GET request is sent to `help.php`, it only provides the 'testName` parameter in the request and doesn't provide a `subtest` value, so it never checks if there's a file in the help table and instead just looks for the markdown help file for the Instruments module. 

Let me know if this makes sense, I can explain it in more detail if necessary. I don't know how to fix this as of now. I can keep looking to see how to edit the GET request to provide the `subtest` parameter, but I haven't figured out where to do that yet.

**Comment by ridz1208** [comment]
@zaliqarosli can you team up with @AlexandraLivadas to figure out what is happening in this module ?

our options would be to either fix it if it doesnt work as intended or remove the module entirely

**Comment by zaliqarosli** [comment]
@ridz1208 yeah sure @AlexandraLivadas wanna slack me or get on a call to explain what's going on?

**Comment by ridz1208** [comment]
@zaliqarosli @AlexandraLivadas have you guys firgured it out ? is it working for  bmi specifically now ?

**Comment by ridz1208** [comment]
fixes #5691

**Comment by zaliqarosli** [comment]
@ridz1208 yeah i fixed it - sent a PR to this PR branch. @AlexandraLivadas can you merge the changes?

File: modules/help_editor/js/help_editor_helper.js [hunk 2]
```diff
@@ -1,5 +1,3 @@
-import swal from 'sweetalert2';
```
Comment (driusan) [inline modules/help_editor/js/help_editor_helper.js:1]: why is this downgrading from swal2 to swal1?

File: php/libraries/NDB_BVL_Instrument.class.inc [hunk 3]
```diff
@@ -253,6 +253,8 @@ abstract class NDB_BVL_Instrument extends NDB_Page
 
         // Sets up page variables such as $this->commentID and $this->form
         $obj->setup($commentID, $page);
+        // Set page name to testName
+        $obj->name = $instrument;
```
Comment (driusan) [inline php/libraries/NDB_BVL_Instrument.class.inc:257]: I think this should go before the setup call in case the setup function intentionally set it to something.

File: modules/help_editor/js/help_editor_helper.js (hunk 2 above)
Comment (AlexandraLivadas) [reply modules/help_editor/js/help_editor_helper.js:1]: When @zaliqarosli was making the changes, she said that this statement threw an error. However, when I added this line back on my local version, I did not get the same error. I'm not sure why this was causing issues for her but not me.

File: php/libraries/NDB_BVL_Instrument.class.inc (hunk 3 above)
Comment (AlexandraLivadas) [reply php/libraries/NDB_BVL_Instrument.class.inc:257]: The setup function being used here only sets the `commentID` and `page` values, so it should have no effect on the `name` value. I can make this change (and test it) anyway though 👍

File: modules/help_editor/js/help_editor_helper.js (hunk 2 above)
Comment (driusan) [reply modules/help_editor/js/help_editor_helper.js:1]: I don't think it should be downgraded.

Comment (zaliqarosli) [reply modules/help_editor/js/help_editor_helper.js:1]: undoing the changes on this file is still giving me the error:

Screen Shot 2020-09-21 at 1 16 02 PM

@laemtl also reported seeing this error in https://github.com/aces/Loris/issues/6940. (Laetitia, any chance you could give this PR a test, with and without these changes to this file?)

@driusan @HenriRabalais @maltheism any of you know how to properly fix this without downgrading to swal1?

Comment (laemtl) [reply modules/help_editor/js/help_editor_helper.js:1]: Yes sure !

Comment (maltheism) [reply modules/help_editor/js/help_editor_helper.js:1]: The reason swal2 isn't accessible is because the help_editor_helper.js is inside the `js` directory and not the `jsx` directory that webpack handles. I think she could move the file to the jsx directory while maybe needing to add it to webpack where the other file the help_editor module uses.

Comment (laemtl) [reply modules/help_editor/js/help_editor_helper.js:1]: @zaliqarosli You are right, there is a bug introduced by #6195. The migration to swal2 introduced problems.

Comment (maltheism) [reply modules/help_editor/js/help_editor_helper.js:1]: @laemtl see htdocs/vendor/sweetalert for the old sweetalert.js that gets accessed anywhere in Loris. I think if we placed the `node_modules/sweetalert/dist/sweetalert2.js` inside that directory or a new one. Then swal2 would be accessible without needing to import.

Comment (laemtl) [reply modules/help_editor/js/help_editor_helper.js:1]: I would like to fix this in a compatible way with my PR #7018. I did fix this for another script by reactifying it.

Comment (zaliqarosli) [reply modules/help_editor/js/help_editor_helper.js:1]: @driusan how would you prefer us to proceed?

Comment (zaliqarosli) [reply modules/help_editor/js/help_editor_helper.js:1]: i think this PR should just fix the bug introduced in https://github.com/aces/Loris/pull/6195/files#diff-319f29c33167f3c507dcb5516ec2578c and the move to sweetalert2 should be tackled in another PR

Comment (driusan) [reply modules/help_editor/js/help_editor_helper.js:1]: I'm not sure I understand why the file can't just be moved from the `js` directory to `jsx` and added to the webpack config so that webpack compiles it and it can use swal2?

Comment (laemtl) [reply modules/help_editor/js/help_editor_helper.js:1]: @driusan Eslint fails with /var/www/html/loris/modules/help_editor/jsx/help_editor_helper.js
33:13  error  A function with a name starting with an uppercase letter should only be used as a constructor  new-cap


```
markdownContent = document.createElement('div');
ReactDOM.render(
       RMarkdown({content: content}),
       markdownContent
);
```

Comment (zaliqarosli) [reply modules/help_editor/js/help_editor_helper.js:1]: wouldn't it be kind of against our repo standard that we're calling a non-react non-jsx file a jsx file and putting it under that directory? help_editor_helper.js isn't a component and doesn't need to be compiled. there's a way to call sweetalert2 with normal JS:

Screen Shot 2020-09-21 at 5 37 34 PM

but using require() also throws an error. surely just making the file a jsx file isn't the right move?

Comment (maltheism) [reply modules/help_editor/js/help_editor_helper.js:1]: @zaliqarosli nodejs, browserify, or webpack supports require() but not javascript on the browser. The browser shouldn't have access to node_modules on the server anyways.

Comment (laemtl) [reply modules/help_editor/js/help_editor_helper.js:1]: @zaliqarosli You are right, I migrated my fix to #7018.

**Review by christinerogers — DISMISSED** [review]

**Comment by christinerogers** [comment]
per Loris meeting discussion today :
* @laemtl will merge the solution from #7018 here 
* unassigning @AlexandraLivadas from this PR (thanks and great work!)
* @laemtl please request re-review from the usual suspects when ready

**Comment by laemtl** [comment]
Updated. As a stated above,  I'm not sure the way I tackle it is the best. I kind of agree that it is weird to have this file under jsx/. I wonder if reactifying it should be preferable? Isn't the plan to completely remove the jQuery dependencies in the future?

**Comment by zaliqarosli** [comment]
this works beautifully now! i agree with laetitia's comments above so i will leave the approving review for someone else. this PR passes testing though

File: modules/help_editor/jsx/help_editor_helper.js [hunk 4]
```diff
@@ -0,0 +1,84 @@
+/* eslint new-cap: ["error", {capIsNewExceptions: ["RMarkdown"]}]*/
```
Comment (maltheism) [inline modules/help_editor/jsx/help_editor_helper.js]: @laemtl shouldn't have this line

File: modules/help_editor/ajax/help.php [hunk 5]
```diff
@@ -32,20 +32,28 @@
...
-        if (!empty($data['created'])) {
-            $data['updated'] = $data['created'];
+            if (empty($data['updated'])) {
+                $data['updated'] = "-";
+                // if document was never updated should display date created
+                if (!empty($data['created'])) {
+                    $data['updated'] = $data['created'];
+                }
+            }
+        } catch (\NotFound $e) {
```
Comment (maltheism) [inline modules/help_editor/ajax/help.php:50]: I'm unsure having a giant try catch here is best compared to encompassing just the lines that throw the error and then handling it from there.

**Comment by maltheism** [comment]
@laemtl I pushed a commit that removes the eslint ignore comment and added two isset() checks to not have the error_logs be populated. I hope you don't mind.

Also I made a comment about using try cache. I think it's fine what you did in this case but it's better to encompass only the lines that throw the error and for making it easier for future developers know where the try cache is actually able to fail. The code can keeps getting modified over time by more being added inside the try {} to make it confusing where it fails.

**Review by maltheism — COMMENTED** [review]
The solution works nicely. I think eventually this ugly jquery code should be replaced by a component that swaps the help editor preview text with whatever is supplied. Since that's actually what's being done with it. None of the jquery is doing anything really fancy besides that.

File: jsx/Markdown.js [hunk 6]
```diff
@@ -40,6 +40,6 @@ Markdown.propTypes = {
 let RMarkdown = React.createFactory(Markdown);
 
 window.Markdown = Markdown;
-window.RMarkdown = RMarkdown;
+window.rMarkdown = RMarkdown;
```
Comment (zaliqarosli) [inline jsx/Markdown.js:43]: @maltheism i'm not sure if this is the PR to incorporate this change because it affects all of Loris, or atleast wherever Markdown is being used. i think changing the Markdown is out of scope. i would agree with laetitia's solution for right now to add the eslint exception comments

File: modules/help_editor/ajax/help.php (hunk 5 above)
Comment (zaliqarosli) [reply modules/help_editor/ajax/help.php:50]: ill try make this change

File: jsx/Markdown.js (hunk 6 above)
Comment (zaliqarosli) [reply jsx/Markdown.js:43]: fair enough! if its limited to this module, i guess that's okay

Comment (maltheism) [reply jsx/Markdown.js:43]: @zaliqarosli that change `window.rMarkdown = RMarkdown;` is just setting the global `window` variable to have "rMarkdown" (Ex. window.rMarkdown). That line removed could still exist in this PR if people are worried about it. Since we would then have window.RMarkdown and window.rMarkdown to use whenever. Although I'm somewhat confident my global search through the code didn't miss anything.

**Review by maltheism — APPROVED** [review]

File: modules/help_editor/jsx/help_editor_helper.js (hunk 4 above)
Comment (laemtl) [reply modules/help_editor/jsx/help_editor_helper.js]: I agree. I was just not sure if renaming RMarkdown was desired as it's a convention accross a lot of modules.

File: jsx/Markdown.js (hunk 6 above)
Comment (laemtl) [reply jsx/Markdown.js:43]: Just to add my grain of salt here...  As this file will/should be rewritten soon, I tend to think that it's preferable to add the eslint ignore line and not modifying the core. Once this file will be reactified, the core change will not be necessary anymore, and this change break the naming policy consistency. I agree that it's preferable to avoid using eslint ignore for long term change though :)

Comment (maltheism) [reply jsx/Markdown.js:43]: @laemtl looking at this code in question. I doubt that's anytime soon.

File: raisinbread/RB_files/RB_help.sql [hunk 7]
```diff
@@ -1,5 +1,6 @@
 SET FOREIGN_KEY_CHECKS=0;
 TRUNCATE TABLE `help`;
 LOCK TABLES `help` WRITE;
+INSERT INTO `help` (`helpID`, `parentID`, `hash`, `topic`, `content`, `created`, `updated`) VALUES (123,-1,'810dc6911c825b55eff684098f2beb19','bmi','The BMI calculator instrument can calculate the BMI and BMI Classification of a visitor. The two required fields for this instrument are the Date of Administration of the instrument and the Examiner name. The height and weight of the visitor must then be entered in either standard or metric units. The instrument will not accept an entry where the height and weight are given in both units. After this information is given, the instrument will calculate the BMI and BMI Classification of the visitor.','2020-09-01 01:03:09',NULL);
```
Comment (christinerogers) [inline raisinbread/RB_files/RB_help.sql:4]:
```suggestion
INSERT INTO `help` (`helpID`, `parentID`, `hash`, `topic`, `content`, `created`, `updated`) VALUES (123,-1,'810dc6911c825b55eff684098f2beb19','bmi','The BMI calculator instrument calculates the BMI and BMI Classification of an individual person. The two required fields for this instrument are the Date of Administration of the instrument and the Examiner name. Enter height and weight in either standard or metric units. After data is entered and the form is saved, the calculated BMI value and BMI Classification of the individual will be displayed.','2020-09-01 01:03:09',NULL);
```

Comment (christinerogers) [reply raisinbread/RB_files/RB_help.sql:4]: just realized this text has been referring to the candidate as "visitor" -- see my fix/edits above

**Review by christinerogers — CHANGES_REQUESTED** [review]
edit to fix the content of the help text blurb.  @laemtl can you able to find a way to accept this suggestion ?   (or Alex could probably find time)

**Review by christinerogers — APPROVED** [review]

**Comment by laemtl** [comment]
This PR and PR#7025 are in conflicts. The last to be merged will have to update raisinbread/RB_files/RB_help.sql to remove the parendID column.

**Comment by christinerogers** [comment]
great catch, thanks @laemtl

**Comment by christinerogers** [comment]
just to check -- is this ready for @driusan  to review, @zaliqarosli @laemtl ?

**Comment by zaliqarosli** [comment]
@christinerogers i believe so! i'll give it one last test

**Comment by laemtl** [comment]
Yes, it's ready for review :)

**Comment by zaliqarosli** [comment]
@driusan should this be closed? ^ i think github did it automatically

**Comment by AlexandraLivadas** [comment]
@zaliqarosli  This PR has been rebased and is ready for testing :)

**Comment by zaliqarosli** [comment]
is discussion still required here?

**Comment by AlexandraLivadas** [comment]
@zaliqarosli  No, I don't think so. I think this was approved a while ago and just needed to be tested and reviewed again on the 23.0 branch

**Review by zaliqarosli — COMMENTED** [review]
everything else looks good. just wondering about one leftover comment. i am happy to review this PR as is though

**Review by zaliqarosli — APPROVED** [review]

**Comment by zaliqarosli** [comment]
could someone test this? i'm having trouble with my dev VM. @jstirling91 would you be interested?

File: modules/help_editor/ajax/help.php [hunk 8]
```diff
@@ -32,20 +32,31 @@
...
-            md5($subpageName ?? $moduleName)
-        );
-    }
+        try {
+            $helpID    = \LORIS\help_editor\HelpFile::hashToID(
+                md5($subpageName ?? $moduleName)
+            );
+            $help_file = \LORIS\help_editor\HelpFile::factory($helpID);
+            $data      = $help_file->toArray();
+
```
Comment (zaliqarosli) [inline modules/help_editor/ajax/help.php:41]:
```suggestion
```

**Review by zaliqarosli — CHANGES_REQUESTED** [review]
everything else looks good! will test now

**Comment by zaliqarosli** [comment]
@AlexandraLivadas any chance you could edit the help_editor .md help file to say "This module displays existing help content for LORIS instrument pages" instead of what's there?

Screen Shot 2021-07-06 at 11 46 37 AM

**Review by ridz1208 — APPROVED** [review]

**Comment by ridz1208** [comment]
@driusan this one is in your hands, it's going to 23 since it's a bugfix requested by IBIS

File: modules/help_editor/help/help_editor.md [hunk 9]
```diff
@@ -1,7 +1,10 @@
 # Help Editor
 
-This module displays existing help content for LORIS modules and pages. 
+This module displays existing help content for LORIS instrument pages
```
Comment (zaliqarosli) [inline modules/help_editor/help/help_editor.md:3]: full stop at the end, sorry for being picky!

**Review by zaliqarosli — CHANGES_REQUESTED** [review]

**Review by zaliqarosli — APPROVED** [review]
LGTM!!

File: modules/help_editor/ajax/help.php [hunk 10]
```diff
@@ -32,20 +32,30 @@
...
+                md5($subpageName ?? $moduleName)
+            );
+            $help_file = \LORIS\help_editor\HelpFile::factory($helpID);
+            $data      = $help_file->toArray();
+        } catch (\NotFound $e) {
+            // Send data with empty strings so that the content can be edited
+            $data = [
+                'content' => '',
+                'topic'   => '',
+                'updated' => '-'
```
Comment (zaliqarosli) [inline modules/help_editor/ajax/help.php:46]: @AlexandraLivadas sorry just noticed, this should be empty

Comment (ridz1208) [reply modules/help_editor/ajax/help.php:46]: @zaliqarosli any other comments??

```suggestion
                'updated' => ''
```

Comment (zaliqarosli) [reply modules/help_editor/ajax/help.php:46]: this should be the last one! i can re-approve once the above suggested change is comitted

**Comment by ridz1208** [comment]
@driusan i think this one is yours as well

**Review by zaliqarosli — APPROVED** [review]
ill approve again since the last commit
