### PR TITLE
[Tools] Fix Raisinbread exporter location

### LINKED ISSUE #4878: [Tools] Fix raisinbread database dump export location
In line 5 of the file [DB_dump_table_data.php](https://github.com/aces/Loris/blob/21.0-release/tools/exporters/DB_dump_table_data.php) the export location should be: BASE_PATH_TO_LORIS/raisinbread/RB_files/RB_TABLE_NAME.sql.

### PR DESCRIPTION
**Pull request by johnsaigle**
### Brief summary of changes

Resolves #4878 by changing the export location to be built using the base URL instead of using a relative path.

Also adds some cleanup.

### CODE REVIEW

File: tools/exporters/DB_dump_table_data.php [hunk 1]
```diff
@@ -56,7 +56,8 @@
 
 // Loop through all tables to generate insert statements for each.
 foreach ($tableNames as $tableName) {
-    $filename = __DIR__ . "/../../raisinbread/RB_files/RB_$tableName.sql";
+    $filename = \NDB_Factory::singleton()->settings()->getBaseURL()
```
Comment (ridz1208) [inline tools/exporters/DB_dump_table_data.php]: @johnsaigle doesnt baseurl return something like "abou-haider-dev.loris.ca" ?? thats not a path

Comment (johnsaigle) [reply tools/exporters/DB_dump_table_data.php]: You're right, my bad. It should be project root or whatever the setting is called

Comment (ridz1208) [reply tools/exporters/DB_dump_table_data.php]: i think thats base
