### PR TITLE
[Imaging Browser] Fix loading of feedback popup for non-QC users

### LINKED ISSUE #4785: [imaging_browser] QC info not viewable if do not have permission to edit the QC
Test Plan section D. MRI-QC:
22. Viewable by all, editable IFF permission imaging_browser_qc

=> When trying to view the QC information with a user that do not have permission imaging_browser_qc, we get a 403 error.

This error got inserted here: https://github.com/aces/Loris/commit/16bb75f7cd813915d43bb61c9bd08329c8b7203c#diff-44bcdd7c78b4cad3c9529f51aa8598f9

### PR DESCRIPTION
**Pull request by driusan**
This should fix item 22 of the imaging browser test plan -- the
page should be viewable by all, regardless of imaging_browser_qc
permission.

Fixes #4785

### CODE REVIEW

**Comment by driusan** [comment]
@cmadjar can you test this? I don't have QC data and can't create any because of #4784, but the page now loads for me without the permission.

File: htdocs/feedback_mri_popup.php [hunk 1]
```diff
@@ -18,16 +18,16 @@
     return;
 }
 
-require_once "FeedbackMRI.class.inc";
```
Comment (driusan) [inline htdocs/feedback_mri_popup.php]: This is in php/libraries. It's loaded by the autoloader on line 13

File: htdocs/router.php [hunk 2]
```diff
@@ -10,13 +10,14 @@
...
-
-
 $url     = ltrim($_SERVER['REQUEST_URI'], "/");
 $request = $_SERVER['REQUEST_URI'];
 
 if ($request != '/'
-    && file_exists(__DIR__ . $request)
+    && (
+        file_exists(__DIR__ . $request)
+        || file_exists(__DIR__ . "/" . $urlpath)
```
Comment (driusan) [inline htdocs/router.php]: this should probably just be the $urlpath line, but I didn't want to risk breaking anything else this late in the release cycle, so I just kept both.

**Comment by driusan** [comment]
@cmadjar that looks like a regression that was introduced at the same time.. I think it should be fixed by the latest commit.

**Comment by driusan** [comment]
Not sure why this is failing travis, I just merged #4761 into it to see if that fixes it (locally for me nothing works without it, and this branch works with php -S with it..)

**Comment by driusan** [comment]
Seems to be passing Travis with FixAjaxRouter merged in, so adding blocked tag for now.
