### PR TITLE
[tools] Tool failures

### LINKED ISSUE #9629: [tools - delete_timepoint] issues
**Describe the bug**

db CandID column not found.

```bash
lorisadmin@test-dev-270:/var/www/Loris/tools/data_integrity/data_deletion$ php delete_timepoint.php delete_timepoint 4136340819 DCC0703 2163
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'CandID' in 'where clause' in /var/www/Loris/src/Database/Query.php:25
Stack trace:
#0 /var/www/Loris/src/Database/Query.php(25): PDOStatement->execute()
#1 /var/www/Loris/php/libraries/Database.class.inc(842): LORIS\Database\Query->count()
#2 /var/www/Loris/php/libraries/Database.class.inc(985): Database->pselectRow()
#3 /var/www/Loris/tools/data_integrity/data_deletion/delete_timepoint.php(85): Database->pselectOne()
#4 {main}
  thrown in /var/www/Loris/src/Database/Query.php on line 25
```

### LINKED ISSUE #9631: [tools - delete_ignored_conflicts] wrong loris instance
**Describe the bug**

The `$lorisInstance` imported from `generic_include` is wrongly named `$loris`.

```bash
lorisadmin@test-dev-270:/var/www/Loris/tools/data_integrity/data_deletion$ php delete_ignored_conflicts.php 
PHP Warning:  Undefined variable $loris in /var/www/Loris/tools/data_integrity/data_deletion/delete_ignored_conflicts.php on line 72
PHP Fatal error:  Uncaught TypeError: NDB_BVL_Instrument::getDDEInstrumentNamesList(): Argument #1 ($loris) must be of type LORIS\LorisInstance, null given, called in /var/www/Loris/tools/data_integrity/data_deletion/delete_ignored_conflicts.php on line 72 and defined in /var/www/Loris/php/libraries/NDB_BVL_Instrument.class.inc:3401
Stack trace:
#0 /var/www/Loris/tools/data_integrity/data_deletion/delete_ignored_conflicts.php(72): NDB_BVL_Instrument::getDDEInstrumentNamesList()
#1 {main}
  thrown in /var/www/Loris/php/libraries/NDB_BVL_Instrument.class.inc on line 3401
```

### LINKED ISSUE #9633: [tools - assign_missing_instruments] Error due to typo
A typo ("Candiate" instead of "Candidate") in assign_missing_instruments causes the script to fail when invoked with the Visit_label argument

To Recreate:
1. Run `php assign_missing_instruments.php V1`
2. See the following error
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.CandiateID' in 'on clause' in /var/www/loris/src/Database/Query.php:46
Stack trace:
#0 /var/www/loris/src/Database/Query.php(46): PDOStatement->execute()
#1 /var/www/loris/tools/assign_missing_instruments.php(144): LORIS\Database\Query->getIterator()
#2 {main}
  thrown in /var/www/loris/src/Database/Query.php on line 46
```

### PR DESCRIPTION
**Pull request by skarya22**
## Brief summary of changes
- These tools had multiple broken parts. Mostly related to CandidateID changes, but also others
- Moved `tools/detect_duplicated_commentids.php` to the deprecated folder as it does not seem relevant to modern LORIS.
image

Closes #9629
Closes #9631
Closes #9633

#### Testing instructions (if applicable)

1. Try running the scripts

### CODE REVIEW

**Comment by driusan** [comment]
@skarya22 PHPCS is failing.

```


FILE: /home/runner/work/Loris/Loris/tools/detect_conflicts.php
--------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
--------------------------------------------------------------------------------
 573 | ERROR | Doc comment for parameter "$lorisInstance" missing
 577 | ERROR | Doc comment for parameter $instruments does not match actual
     |       | variable name $lorisInstance
 578 | ERROR | Doc comment for parameter $confirm does not match actual
     |       | variable name $instruments
--------------------------------------------------------------------------------
```

**Comment by jeffersoncasimir** [comment]
@skarya22 This PR appears to be rebased to 26.0-release and not main

File: tools/fix_timepoint_date_problems.php [hunk 1]
```diff
@@ -81,7 +81,20 @@
...
 
 // CandID
-$candID = new CandID($argv[2]);
+try {
+    $candID = new CandID($argv[2]);
+} catch (DomainException $e) {
+    fwrite(
+        STDERR,
+        "Error: invalid 2st argument CandID ({$argv[2]}).\n " .
+        "It has to be a 6-digit number\n"
```
Comment (driusan) [inline tools/fix_timepoint_date_problems.php:90]: No it doesn't.

Comment (skarya22) [reply tools/fix_timepoint_date_problems.php:90]: Sorry! That was copied over from below, did not write that myself

**Review by jeffersoncasimir — CHANGES_REQUESTED** [review]
Unfortunately, none of these errors seem caused by these changes, but this PR is shining a light on many existing issues. 

All scripts were tested with valid inputs which each of their different forks (ex: `tosql`, `confirm`). They were not tested with "invalid inputs" (ex: non-existing IDs). Non-mentions can be assumed to be tested and functional (no fatal errors).

I ran `tools/data_integrity/data_deletion/delete_candidate.php` with `confirm` and got the following error:

```
Dropping all DB entries for candidate CandID: 648507 And PSCID: DRV0005
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`jcasimir_test_26`.`dataquery_run_results`, CONSTRAINT `dataquery_run_results_ibfk_1` FOREIGN KEY (`CandidateID`) REFERENCES `candidate` (`ID`)) in /var/www/Loris/php/libraries/Database.class.inc:630
Stack trace:
#0 /var/www/Loris/php/libraries/Database.class.inc(630): PDO->exec()
#1 /var/www/Loris/tools/data_integrity/data_deletion/delete_candidate.php(367): Database->delete()
#2 /var/www/Loris/tools/data_integrity/data_deletion/delete_candidate.php(118): deleteCandidate()
#3 {main}
  thrown in /var/www/Loris/php/libraries/Database.class.inc on line 630
```


I ran `tools/data_integrity/data_deletion/delete_timepoint.php` with `tosql` and got the following error:

```
PHP Fatal error:  Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /var/www/Loris/tools/data_integrity/data_deletion/delete_timepoint.php:503
Stack trace:
#0 /var/www/Loris/tools/data_integrity/data_deletion/delete_timepoint.php(503): fwrite()
#1 /var/www/Loris/tools/data_integrity/data_deletion/delete_timepoint.php(460): _exportSQL()
#2 /var/www/Loris/tools/data_integrity/data_deletion/delete_timepoint.php(120): deleteTimepoint()
#3 {main}
  thrown in /var/www/Loris/tools/data_integrity/data_deletion/delete_timepoint.php on line 503
```

I ran `tools/data_integrity/data_deletion/delete_timepoint.php` with `confirm` and got the following error:

```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`jcasimir_test_26`.`physiological_file`, CONSTRAINT `FK_session_ID` FOREIGN KEY (`SessionID`) REFERENCES `session` (`ID`)) in /var/www/Loris/php/libraries/Database.class.inc:630
Stack trace:
#0 /var/www/Loris/php/libraries/Database.class.inc(630): PDO->exec()
#1 /var/www/Loris/tools/data_integrity/data_deletion/delete_timepoint.php(365): Database->delete()
#2 /var/www/Loris/tools/data_integrity/data_deletion/delete_timepoint.php(120): deleteTimepoint()
#3 {main}
  thrown in /var/www/Loris/php/libraries/Database.class.inc on line 630
```

`tools/detect_conflicts.php` has this error, when used with `-i`:

```
PHP Fatal error:  Uncaught TypeError: getCurrentUnresolvedConflicts(): Return value must be of type array, LORIS\Database\Query returned in /var/www/Loris/tools/detect_conflicts.php:358
Stack trace:
#0 /var/www/Loris/tools/detect_conflicts.php(190): getCurrentUnresolvedConflicts()
#1 {main}
  thrown in /var/www/Loris/tools/detect_conflicts.php on line 358
```

`detect_duplicated_commentids.php` has an error, similar to the previous:

```
PHP Fatal error:  Uncaught Error: Cannot use object of type LORIS\Database\Query as array in /var/www/Loris/tools/detect_duplicated_commentids.php:199
Stack trace:
#0 /var/www/Loris/tools/detect_duplicated_commentids.php(127): getCommentIDs()
#1 {main}
  thrown in /var/www/Loris/tools/detect_duplicated_commentids.php on line 199
```

Not sure what to make of this: `php fix_timepoint_date_problems.php add_instrument 300001 1 aosi`

```
Error: failed to add the instrument aosi for timepoint (1):
Error: Database user named lorisadmin does not exist. Please create and then retry script
```

**Comment by skarya22** [comment]
@jeffersoncasimir Thank you for catching those! Resolved them

**Review by jeffersoncasimir — CHANGES_REQUESTED** [review]
I ran `tools/data_integrity/data_deletion/delete_candidate.php` with `tosql` and got the following error:
```
PHP Fatal error:  Uncaught TypeError: preg_match_all(): Argument #2 ($subject) must be of type string, array given in /var/www/Loris/tools/data_integrity/data_deletion/delete_candidate.php:201
```

I ran `tools/data_integrity/data_deletion/delete_candidate.php` with `confirm` and got the following error:

```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`jcasimir_test_26`.`physiological_event_file`, CONSTRAINT `FK_physio_file_ID` FOREIGN KEY (`PhysiologicalFileID`) REFERENCES `physiological_file` (`PhysiologicalFileID`)) in /var/www/Loris/php/libraries/Database.class.inc:630
```
I ran `tools/data_integrity/data_deletion/delete_timepoint.php` with `confirm` and got the following error (same as `delete_candidate` right above -- `tosql` is now functional):
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`jcasimir_test_26`.`physiological_event_file`, CONSTRAINT `FK_physio_file_ID` FOREIGN KEY (`PhysiologicalFileID`) REFERENCES `physiological_file` (`PhysiologicalFileID`)) in /var/www/Loris/php/libraries/Database.class.inc:630
```

I am struggling to test `tools/detect_conflicts.php` in a meaningful way. The previous error is gone, but I can't get it to work with any instrument; it always results in: `the instrument is not set or there are no commentids`. When I do `-i all` it will fail at this error that will be addressed by another PR:
```
PHP Fatal error:  Uncaught OutOfBoundsException: Invalid field Examiner for instrument bmi in /var/www/Loris/php/libraries/NDB_BVL_Instrument.class.inc:1412
```

I ran `tools/detect_duplicated_commentids.php` and got the following error:
```
PHP Fatal error:  Uncaught DomainException: Attempt to use pselectRow on a query that returns multiple rows in /var/www/Loris/php/libraries/Database.class.inc:848
```

`tools/fix_timepoint_date_problems.php` appears to work as expected!

**Review by jeffersoncasimir — CHANGES_REQUESTED** [review]
I ran `tools/data_integrity/data_deletion/delete_candidate.php`: Final line should delete `candidate.ID`. (error below likely applies as well -- deletion did not occur, so "Integrity constraint violation" not triggered)


I ran tools/data_integrity/data_deletion/delete_timepoint.php with confirm and got the following error:
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`jcasimir_test_26`.`physiological_task_event`, CONSTRAINT `FK_event_file` FOREIGN KEY (`EventFileID`) REFERENCES `physiological_event_file` (`EventFileID`)) in /var/www/Loris/php/libraries/Database.class.inc:630
```

I successfully tested `tools/detect_conflicts.php`. Only 2 tools to go!

**Comment by skarya22** [comment]
@jeffersoncasimir I think that deletion should occur in delete_candidate as it is deleting by CandID using the CandID, not CandidateID.
image

For timepoints, I decided to make it consistent with other files, where if a physiological_file exists for the session then you have to delete that first.
Thanks!!

**Review by jeffersoncasimir — APPROVED** [review]
All modified scripts have been tested relatively thoroughly and appear to work as expected!

**Comment by skarya22** [comment]
@jeffersoncasimir can you re-review before it is sent to Dave for final review?

It is just one space added before an equals sign

**Review by jeffersoncasimir — APPROVED** [review]
