### PR TITLE
Candidate parametrers fail to load

### LINKED ISSUE #5791: [Candidate Parameters] Cannot load candidate parameters
When a user only has the `candidate_parameter_view` permission and he/she attempts to access the candidate parameters of a candidate, an error page is shown (text displayed: `An error occurred loading the form`).

### PR DESCRIPTION
**Pull request by nicolasbrossard**
## Brief summary of changes

When you only have the `candidate_parameter_view` permission, you can access the candidate parameter page but when it loads, an error page is shown with text: `An error occurred when loading the form`.

Fixes #5791

### CODE REVIEW

File: modules/candidate_parameters/ajax/getData.php [hunk 1]
```diff
@@ -15,7 +15,9 @@
 use \LORIS\StudyEntities\Candidate\CandID;
 
 $user = \NDB_Factory::singleton()->user();
-if (!$user->hasPermission('candidate_parameter_edit')) {
+if (!$user->hasPermission('candidate_parameter_edit')
+    && !$user->hasPermission('candidate_parameter_view')
```
Comment (jesscall) [inline modules/candidate_parameters/ajax/getData.php]: You could also use the following fucntion:

```
if (!$user->hasAnyPermission(
      array(
             'candidate_parameter_edit',
             'candidate_parameter_view'
      )
)) { ...
```

Comment (nicolasbrossard) [reply modules/candidate_parameters/ajax/getData.php]: Mmmm...Didn't know about that one! Thanks!

**Comment by johnsaigle** [comment]
Transitory Travis failure due to #5719. Restarting Travis.
