### PR TITLE
[Deprecated DQT] Fix type error in demographic import script

### LINKED ISSUE #9507: LORIS v26.0.0 - CouchDB_Import_Demographics.php error
### Discussed in https://github.com/aces/Loris/discussions/9499

<div type='discussions-op-text'>

<sup>Originally posted by **Johan-Peralta** December  3, 2024</sup>
Hi, I am getting the following error when executing the CouchDB_Import_Demographics.php script on LORIS v26.0.0:

```
/var/www/loris/tools$ php CouchDB_Import_Demographics.php
Updating Config:BaseConfig: unchanged contentsDemographics_Session_HBN0000_VIS1: new
Demographics_Session_DCC0000_VIS1: new
PHP Fatal error:  Uncaught TypeError: Project::getProjectFromID(): Argument #1 ($projectID) must be of type ProjectID, int given, called in /var/www/loris/tools/CouchDB_Import_Demographics.php on line 380 and defined in /var/www/loris/php/libraries/Project.class.inc:105
Stack trace:
#0 /var/www/loris/tools/CouchDB_Import_Demographics.php(380): Project::getProjectFromID()
#1 /var/www/loris/tools/CouchDB_Import_Demographics.php(496): CouchDBDemographicsImporter->_updateDataDict()
#2 /var/www/loris/tools/CouchDB_Import_Demographics.php(512): CouchDBDemographicsImporter->run()
#3 {main}
  thrown in /var/www/loris/php/libraries/Project.class.inc on line 105

```
The projects seem to be properly setup in the MySQL side.
Any ideas on what could be causing the error?

Any help will be greatly appreciated, Johan</div>

### PR DESCRIPTION
**Pull request by driusan**
Fix type error in CouchDB_Import_Demographics script.

Resolves #9507

### CODE REVIEW

File: tools/CouchDB_Import_Demographics.php [hunk 1]
```diff
@@ -378,7 +378,7 @@ function _updateDataDict()
         $projects = \Utility::getProjectList();
         foreach ($projects as $projectID => $project) {
             $projectAlias = \Project::getProjectFromID(
-                ProjectID::singleton($projectID)
+                new ProjectID(strval($projectID))
```
Comment (Johan-Peralta) [inline tools/CouchDB_Import_Demographics.php:381]: This change fixed the script failure.
Thanks.
