### PR TITLE
[battery_manager] Fixing testing bugs

### LINKED ISSUE #6955: [Battery Manager] Min Age and Max age validation
- Min age can be greater than max age.
- When a negative Min/Max age is entered, the error message is too vague (Could not add entry to the Test Battery)

## To reproduce
* Click on New Test
*  Fill in a Max Age and Min age such that Min is greater than Max
* Notice the absence of errors

## Expected behaviour
We expect an error to notify the user that the values are not valid.

### LINKED ISSUE #6957: [Battery Manager] Console errors
A few errors are logged in the console, without breaking any functionality:
- Warning: Failed prop type: Invalid prop `onSubmit` of type `function` supplied to `Modal`, expected `object`.
    in Modal (created by BatteryManagerIndex)
    in BatteryManagerIndex react.development.js:1641:17
- Uncaught (in promise) Could not add entry to the Test Battery (when error in form)
- Uncaught (in promise) undefined when submit the form with no filled fields
- Error 500 with testendpoint/ when submit the form with Instrument order > 127

### LINKED ISSUE #6958: [Battery Manager] Form validation problem
If someone submits a new empty entry (no data filled in), it triggers red marks on form inputs. 
They do not disappear if another entry is loaded by clicking the edit button, reloading the same form with the red marks with the new data which is valid.

### PR DESCRIPTION
**Pull request by HenriRabalais**
## Brief summary of changes
Fixes bugs validation bugs and console errors found in battery manager during the testing round.

#### Link(s) to related issue(s)
* Resolves #6957
* Resolves #6958 
* Resolves #6955

### CODE REVIEW

File: jsx/Modal.js [hunk 1]
```diff
@@ -132,11 +132,13 @@ class Modal extends Component {
...
     const submitButton = () => {
       if (onSubmit) {
+        const submit = () => onSubmit().then(() => this.props.onClose())
+        .catch(() => {});
         return (
           <div style={submitStyle}>
             <ButtonElement
               label="Submit"
-              onUserInput={() => onSubmit().then(() => this.props.onClose())}
+              onUserInput={submit}
```
Comment (HenriRabalais) [inline jsx/Modal.js:141]: This fixes one of the uncaught in promise errors

File: modules/battery_manager/jsx/batteryManagerIndex.js [hunk 2]
```diff
@@ -66,9 +66,9 @@ class BatteryManagerIndex extends Component {
     return new Promise((resolve, reject) => {
       return fetch(url, {credentials: 'same-origin', method: method})
       .then((resp) => resp.json())
-      .then((data) => this.setState({[state]: data}, resolve()))
+      .then((data) => this.setState({[state]: data}, resolve))
       .catch((error) => {
-        this.setState({error: true}, reject());
+        this.setState({error: true}, reject);
```
Comment (HenriRabalais) [inline modules/battery_manager/jsx/batteryManagerIndex.js:71]: removing unnecessary function calls.

File: modules/battery_manager/jsx/batteryManagerIndex.js [hunk 3]
```diff
@@ -211,7 +211,7 @@ class BatteryManagerIndex extends Component {
    * Close the Form
    */
   closeForm() {
-    this.setState({add: false, edit: false, test: {}});
+    this.setState({add: false, edit: false, test: {}, errors: {}});
```
Comment (HenriRabalais) [inline modules/battery_manager/jsx/batteryManagerIndex.js:214]: resetting errors upon form close so that they don't appear across forms.

File: modules/battery_manager/jsx/batteryManagerIndex.js [hunk 4]
```diff
@@ -470,18 +470,26 @@ class BatteryManagerIndex extends Component {
...
+        errors.ageMinDays = 'This field must be 0 or greater';
       }
       if (test.ageMaxDays == null) {
         errors.ageMaxDays = 'This field is required';
+      } else if (test.ageMaxDays < 0) {
+        errors.ageMaxDays = 'This field must be 0 or greater';
+      }
+      if (test.ageMinDays > test.ageMaxDays) {
+        errors.ageMinDays = 'Minimum age must be lesser than maximum age.';
+        errors.ageMaxDays = 'Maximum age must be greater than minimum age.';
```
Comment (HenriRabalais) [inline modules/battery_manager/jsx/batteryManagerIndex.js:483]: Adding form validation for age

File: modules/battery_manager/jsx/batteryManagerIndex.js [hunk 5]
```diff
@@ -470,18 +470,26 @@ class BatteryManagerIndex extends Component {
...
       if (test.stage == null) {
         errors.stage = 'This field is required';
       }
 
       if (Object.entries(errors).length === 0) {
-        this.setState({errors}, resolve(test));
+        this.setState({errors}, () => resolve(test));
       } else {
-        this.setState({errors}, reject());
+        this.setState({errors}, reject);
```
Comment (HenriRabalais) [inline modules/battery_manager/jsx/batteryManagerIndex.js:492]: removing unnecessary function calls.

File: modules/battery_manager/jsx/batteryManagerIndex.js [hunk 6]
```diff
@@ -470,18 +470,26 @@ class BatteryManagerIndex extends Component {
...
+        errors.ageMinDays = 'Minimum age must be lesser than maximum age.';
+        errors.ageMaxDays = 'Maximum age must be greater than minimum age.';
       }
       if (test.stage == null) {
         errors.stage = 'This field is required';
       }
 
       if (Object.entries(errors).length === 0) {
-        this.setState({errors}, resolve(test));
+        this.setState({errors}, () => resolve(test));
```
Comment (HenriRabalais) [inline modules/battery_manager/jsx/batteryManagerIndex.js:490]: passing as function instead of calling function directly

File: modules/battery_manager/php/testendpoint.class.inc [hunk 7]
```diff
@@ -257,9 +257,18 @@ class TestEndpoint implements RequestHandlerInterface
...
+        }
         if (!isset($test->row['ageMaxDays'])) {
             $errors[] = 'Maximum age is a required field.';
         }
+        if (isset($test->row['ageMaxDays']) && $test->row['ageMaxDays'] < 0) {
+            $errors[] = 'Maximum age must be greater than 0.';
+        }
+        if ($test->row['ageMaxDays'] < $test->row['ageMinDays']) {
+            $errors[] = 'Maximum age must be greater than minimum age.';
+        }
```
Comment (HenriRabalais) [inline modules/battery_manager/php/testendpoint.class.inc:271]: Adding backend validation for the new validation added to the front end

File: jsx/Modal.js [hunk 8]
```diff
@@ -169,7 +171,7 @@ class Modal extends Component {
 
 Modal.propTypes = {
   title: PropTypes.string,
-  onSubmit: PropTypes.object,
+  onSubmit: PropTypes.func,
```
Comment (HenriRabalais) [inline jsx/Modal.js:174]: resolves the console warning about wrong prop type

File: modules/battery_manager/php/testendpoint.class.inc [hunk 9]
```diff
@@ -257,12 +257,27 @@ class TestEndpoint implements RequestHandlerInterface
...
         if (!isset($test->row['stage'])) {
             $errors[] = 'Stage is a required field.';
         }
+        if (isset($test->row['instrumentOrder']) &&
+            ($test->row['instrumentOrder'] > 127 ||
+            $test->row['instrumentOrder'] < -127)
+        ) {
+            $errors[] = 'Instrument order must be between -127 and 127';
+        }
```
Comment (HenriRabalais) [inline modules/battery_manager/php/testendpoint.class.inc:280]: Adds validation for instrument Order

File: modules/battery_manager/jsx/batteryManagerIndex.js [hunk 10]
```diff
@@ -254,10 +254,10 @@ class BatteryManagerIndex extends Component {
       this.checkDuplicate(test)
       .then((test) => this.validateTest(test))
       .then((test) => this.postData(
-          this.props.testEndpoint+test.id,
+          this.props.testEndpoint+(test.id || ''),
```
Comment (HenriRabalais) [inline modules/battery_manager/jsx/batteryManagerIndex.js:257]: This was appearing as `undefined` in the network and was confusing. This resolves that issue.

Comment (HenriRabalais) [inline modules/battery_manager/jsx/batteryManagerIndex.js:257]: This was appearing as `undefined` in the network and was confusing. This resolves that issue.

**Review by laemtl — CHANGES_REQUESTED** [review]
Awesome work! The only thing I noticed is that there is still an error with testendpoint/ when submit the form with Instrument order > 127, but now it's a 400, not a 500.

**Comment by HenriRabalais** [comment]
@laemtl I think a 400 error should be fine since that properly describes what's happening. Is the user receiver an error message indicating what made they submission a bad request?

**Comment by laemtl** [comment]
Your point is valid. I think proper validation to avoid the propagation of the error is a better option, but as you said, the error also makes sense so it does not hurt much to live with it.

**Review by laemtl — APPROVED** [review]

**Comment by ridz1208** [comment]
@laemtl do you mind testing this PR ? (i see you approved it but no sign of manual testing)

@driusan It's ready for your review right after

**Comment by laemtl** [comment]
@ridz1208 @driusan Ready for review.
