### PR TITLE
[imaging_uploader] Fix bug with auto-filling compound visit labels

### LINKED ISSUE #6569: [imaging_uploader] bug with auto-fill visit label
**Describe the bug**
The auto-fill feature on the imaging_uploader is only populating part of the visit label name. 
Ex: Visit label = `Initial_MRI`, auto-fill is only inputing `Initial` and there is no way to correct it since fields are disabled. I presume it's just a regex thing.

Screen Shot 2020-05-21 at 3 06 44 PM

**What did you expect to happen?**
Proper population of the visit label.

**Browser Environment (please complete the following information):**
- OS: 
- Browser: Chrome 
- Version: 23.0

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: 23.0
- Linux distribution and Version: Ubuntu 16.04.6
- MySQL/MariaDB Version: MySQL 5.7

### PR DESCRIPTION
**Pull request by jesscall**
## Brief summary of changes
For compound visit labels that contain underscores (EX: `Initial_MRI`), the auto-fill feature was not populating the full visit name due to how the file name was being spliced. This PR addresses that issue and ensures that full visit label is populated.

#### Testing instructions (if applicable)

1. Try attaching a file with visit label containing an underscore. (EX: `Initial_MRI`)
2. Try attaching a file with visit label that does not contain underscores. (EX: `V1`)
3. Repeat steps 1 & 2 for both cases where Phantom Scan = `yes` & `no`

#### Link(s) to related issue(s)

* Resolves #6569

### CODE REVIEW

File: modules/imaging_uploader/jsx/UploadForm.js [hunk 1]
```diff
@@ -53,10 +53,11 @@ class UploadForm extends Component {
         delete formData.visitLabel;
       } else if (typeof formData.mriFile !== 'undefined') {
         let patientName = formData.mriFile.name.replace(/\.[a-z]+\.?[a-z]+?$/i, '');
-        let ids = patientName.split('_', 3);
+        let ids = patientName.split('_');
         formData.candID = ids[1];
         formData.pSCID = ids[0];
-        formData.visitLabel = ids[2];
+        ids.splice(0, 2);
```
Comment (jesscall) [inline modules/imaging_uploader/jsx/UploadForm.js:59]:
```suggestion
        // visitLabel can contain underscores
        // join the remaining elements of patientName and use as visitLabel
        ids.splice(0, 2);
```

File: modules/imaging_uploader/jsx/UploadForm.js [hunk 2]
```diff
@@ -65,10 +66,11 @@ class UploadForm extends Component {
     if (field === 'mriFile') {
       if (value.name && formData.IsPhantom === 'N') {
         let patientName = value.name.replace(/\.[a-z]+\.?[a-z]+?$/i, '');
-        let ids = patientName.split('_', 3);
+        let ids = patientName.split('_');
         formData.candID = ids[1];
         formData.pSCID = ids[0];
-        formData.visitLabel = ids[2];
+        ids.splice(0, 2);
```
Comment (jesscall) [inline modules/imaging_uploader/jsx/UploadForm.js:72]:
```suggestion
        // visitLabel can contain underscores
        // join the remaining elements of patientName and use as visitLabel
        ids.splice(0, 2);
```
