### PR TITLE
[imaging_uploader] Fix: Selection Filter Logic

### LINKED ISSUE #10310: [imaging_uploader] Selection Filter not working

### PR DESCRIPTION
**Pull request by arnav-makkar**
## Brief summary of changes

This PR fixes the broken Selection Filter in the Imaging Uploader module. Previously, filtering would return 0 results regardless of input.

### Changes
- **Prop Name Correction**: Updated `ImagingUploader.js` to pass `filters` instead of `Filter` to the `DataTable` component, matching the expected prop name.
- **Filter Configuration**: Added the missing filter configuration objects (mapping filter names to column indices) to the `fields` array passed to `DataTable`.

### Verification
- Verified that the `DataTable` now correctly receives filter data.
- Confirmed that entering values in the DCCID, PSCID, or Visit Label filters correctly filters the table rows.

https://github.com/user-attachments/assets/fa13f839-78f2-4fc5-9d04-e767001281a9

#### Link(s) to related issue(s)

* Resolves #10310

### CODE REVIEW

File: modules/imaging_uploader/jsx/ImagingUploader.js [hunk 1]
```diff
@@ -282,15 +282,24 @@ class ImagingUploader extends Component {
...
               fields={this.state.data.Headers.map(
-                (header) => {
+                (header, index) => {
+                  let filter = undefined;
+                  if (index === 2) {
+                    filter = {name: 'candID'};
+                  } else if (index === 3) {
+                    filter = {name: 'pSCID'};
+                  } else if (index === 4) { // Visit_label
+                    filter = {name: 'visitLabel', type: 'select'};
```
Comment (HenriRabalais) [inline modules/imaging_uploader/jsx/ImagingUploader.js]: looking at the `Datatable` component, I don't believe the `filter` value of the `fields` prop makes use of a `type` key, so I think that can be removed.

**Review by HenriRabalais — CHANGES_REQUESTED** [review]
Tested and it appears to fix the filter! I think this module needs to be refactored to make use of the `FilterableDataTable` to abstract some of this logic. Once this requested change is made I will approve the PR.

File: modules/imaging_uploader/jsx/ImagingUploader.js (hunk 1 above)
Comment (arnav-makkar) [reply modules/imaging_uploader/jsx/ImagingUploader.js]: Thank you for pointing this out.
I verified it's unused in the component and have removed it now.

File: modules/imaging_uploader/jsx/ImagingUploader.js [hunk 2]
```diff
@@ -282,15 +282,24 @@ class ImagingUploader extends Component {
...
-                (header) => {
+                (header, index) => {
+                  let filter = undefined;
+                  if (index === 2) {
+                    filter = {name: 'candID'};
+                  } else if (index === 3) {
+                    filter = {name: 'pSCID'};
+                  } else if (index === 4) { // Visit_label
+                    filter = {name: 'visitLabel'};
+                  }
```
Comment (HenriRabalais) [inline modules/imaging_uploader/jsx/ImagingUploader.js:293]:
```suggestion
                (header, index) => {
                  let filter = {};
                  if (header === 'DCCID') {
                    filter = {name: 'candID'};
                  } else if (header === 'PSCID') {
                    filter = {name: 'pSCID'};
                  } else if (header === 'Visit Label') {
                    filter = {name: 'visitLabel'};
                  }
```

**Review by HenriRabalais — CHANGES_REQUESTED** [review]
Actually, after discussion with @ridz1208 perhaps it would be better to make these modifications to make it semantic clear which column each of these filters is targeting, that would be awesome.

File: modules/imaging_uploader/jsx/ImagingUploader.js (hunk 2 above)
Comment (arnav-makkar) [reply modules/imaging_uploader/jsx/ImagingUploader.js:293]: This seems like a much better approach and looks way cleaner than my version. I'm happy to go ahead with these changes. 

Thank you!

File: modules/imaging_uploader/jsx/ImagingUploader.js [hunk 3]
```diff
@@ -282,15 +282,24 @@ class ImagingUploader extends Component {
             <DataTable
               data={this.state.data.Data}
               fields={this.state.data.Headers.map(
-                (header) => {
+                (header, index) => {
+                  let filter = {};
+                  if (header === 'DCCID') {
+                    filter = {name: 'candID'};
+                  } else if (header === 'PSCID') {
+                    filter = {name: 'pSCID'};
```
Comment (skarya22) [inline modules/imaging_uploader/jsx/ImagingUploader.js:290]: Just randomly came across this -- is there a reason this is pSCID instead of PSCID?

Comment (HenriRabalais) [reply modules/imaging_uploader/jsx/ImagingUploader.js:290]: That's how it's declared on the backend and it needs to match the key for the filter to work properly.

https://github.com/aces/Loris/blob/cb2fdab84a3929cd656afab2116a8d285666be2b/modules/imaging_uploader/php/imaging_uploader.class.inc#L168
