### PR TITLE
[IssueTracker] Fix for "othersWatching" history tracking

### LINKED ISSUE #8874: [issue_tracker] Changes in "Others watching" is not being tracked in the history.
Changes in "Others watching" is not being tracked in the history.

**To Reproduce**
1. Edit an existing issue
2. Add or remove a user from "Others watching" multiselect input.
3. Save and check the history.

**What did you expect to happen?**
The change in "Others watching" should be visible in the history.
  
**Server Environment:**  
- LORIS Version: 25.0

### PR DESCRIPTION
**Pull request by sanjay-thiyagarajan**
## Brief summary of changes

- Tracks "Others Watching" in issue history

#### Link(s) to related issue(s)

* Resolves #8874

### CODE REVIEW

**Review by racostas — APPROVED** [review]
LGTM.

File: SQL/0000-00-00-schema.sql [hunk 1]
```diff
@@ -1531,7 +1531,7 @@ CREATE TABLE `issues_history` (
   `issueHistoryID` int(11) unsigned NOT NULL AUTO_INCREMENT,
   `newValue` longtext NOT NULL,
   `dateAdded` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
-  `fieldChanged` enum('assignee','status','comment','sessionID','centerID','title','category','module','lastUpdatedBy','priority','candID') NOT NULL DEFAULT 'comment',
+  `fieldChanged` enum('assignee','status','comment','sessionID','centerID','title','category','module','lastUpdatedBy','priority','candID', 'watching') NOT NULL DEFAULT 'comment',
```
Comment (racostas) [inline SQL/0000-00-00-schema.sql:1534]:
```suggestion
  `fieldChanged` enum('assignee','status','comment','sessionID','centerID','title','category','module','lastUpdatedBy','priority','candID','watching') NOT NULL DEFAULT 'comment',
```

Comment (racostas) [reply SQL/0000-00-00-schema.sql:1534]: one cosmetic change.

**Comment by racostas** [comment]
This one is ready !

**Comment by racostas** [comment]
^ @driusan

**Review by racostas — APPROVED** [review]
LGTM.
