### PR TITLE
[instrument_manager] Fix write permission

### LINKED ISSUE #7129: [23.0][instrument_manager] Write permissions not being used
**Describe the bug**
The `instrument_manager_write` permission is not really being used. If you do not have the permission, you can still see and access the upload tab. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `Instrument Manager`
2. Remove `instrument_manager_write`, and refresh the module. Nothing changes.

**What did you expect to happen?**
For permissions to be more granular and affect the usage of the module.

### PR DESCRIPTION
**Pull request by CamilleBeau**
## Brief summary of changes
This PR makes it so that users with the instrument_manager_write permission are able to upload on instrument manager, and people without this permission do not have access to the upload tab. 

- [x] Have you updated related documentation?

#### Testing instructions (if applicable)

1. Access the instrument manager page with only the view permission. Make sure that you only see the "Browse" tab, and not the "Upload" tab. 
2. Attempt to go directly to the upload tab by adding /instrument_manager/?#upload to your base link. Make sure that the page loads with "You do not have access to this page"
3. Give yourself the instrument_manager_write permission.
4. Make sure that you now have access to the upload tab, either by reloading the page and clicking on the tab, or by navigating directly to the link.
5. Attempt to upload a file. Ensure that you are not given the "forbidden" error (you may get other errors though).

#### Link(s) to related issue(s)

* Resolves #7129

### CODE REVIEW

**Comment by driusan** [comment]
shouldn't this go to the 23 branch?

**Comment by jesscall** [comment]
@CamilleBeau Dave is right, please rebase! :)

**Comment by CamilleBeau** [comment]
My bad, rebased!

File: modules/instrument_manager/jsx/instrumentManagerIndex.js [hunk 1]
```diff
@@ -103,11 +103,14 @@ class InstrumentManagerIndex extends Component {
...
-      {id: 'upload', label: 'Upload'},
     ];
 
+    if (this.props.hasPermission('instrument_manager_write')) {
+      tabs.push({id: 'upload', label: 'Upload'});
+    }
+
     const feedback = () => {
-      if (!this.state.data.caninstall) {
+      if (!this.state.data.caninstall && this.props.hasPermission('instrument_manager_write')) {
```
Comment (driusan) [inline modules/instrument_manager/jsx/instrumentManagerIndex.js:113]: out of curiousity is there a reason to do it this way instead of incorporating it into the "caninstall"?

Comment (CamilleBeau) [reply modules/instrument_manager/jsx/instrumentManagerIndex.js:113]: I didn't want to put it in the function `isQuatUserConfigured` which is used for `caninstall` in instrument_manager.class.inc because it seemed specific to whether the user is configured properly in the sql DB. But I could put it in that function if you think it's better, or add it to line 322 in instrument_manager.class.inc where caninstall is set.

Comment (driusan) [reply modules/instrument_manager/jsx/instrumentManagerIndex.js:113]: I would have probably put it in toArray where caninstall is set to avoid needing to do permission checks in javascript, but it's fine the way it is since it looks like you need to do some js side checks anyways..

**Review by jesscall — APPROVED** [review]
