### PR TITLE
[CouchDB MRI Importer] Account for selected file(s)

### LINKED ISSUE #6054: Couch_MRI_Importer script broken
**Describe the bug**
Somewhere in LORIS 17.0 branch maintenance the query on the selected flag in the MRI Couchdb importer was removed. this is a critical part of the script.

**Additional context**
PR #5933 was created to fix the issue but required more work to be done.

Someone on the imaging team should take charge of this

### PR DESCRIPTION
**Pull request by jesscall**
## Brief summary of changes
This PR helps resolve the issue reported in #6054, in which the argument checking for selected files was removed from the MRI importer script. This PR also adds support for the following cases: (a) multiple selected files, (b) no selected files.

The work here is taken from a previous PR (#5933), with some amendments.

#### Testing instructions (if applicable)

1. Run the script and check DQT to make sure that the correct files and QC info was imported.

#### Link(s) to related issue(s)

* Resolves #6054

### CODE REVIEW

File: tools/CouchDB_MRI_Importer.php [hunk 1]
```diff
@@ -118,24 +118,98 @@ function _generateCandidatesQuery($ScanTypes)
...
+                    . '  WHEN 1 '
+                    . '    THEN (' .
+                        $this->_getQueryForSelectedFiles(
+                            'f.File',
+                            $scantype
+                        )
+                    . ') '
+                    . '  WHEN 0 '
+                    . '    THEN "No selected file" '
+                    . '  ELSE "Multiple Selected files"'
```
Comment (cmadjar) [inline tools/CouchDB_MRI_Importer.php:147]:
```suggestion
                    . '  ELSE "Multiple selected files"'
```

File: tools/CouchDB_MRI_Importer.php [hunk 2]
```diff
@@ -118,24 +118,98 @@ function _generateCandidatesQuery($ScanTypes)
...
+                    . ' CASE (' .
+                            $this->_getQueryForSelectedFiles(
+                                'count(*)',
+                                $scantype
+                            )
+                    . ') '
+                    . '  WHEN 1 '
+                    . '    THEN ('
+                    .        $this->_getQueryForSelectedFiles(
+                        'COALESCE(fqs.QCStatus, "No Qc on selected file")',
```
Comment (cmadjar) [inline tools/CouchDB_MRI_Importer.php:171]:
```suggestion
                        'COALESCE(fqs.QCStatus, "No QC on selected file")',
```

File: tools/CouchDB_MRI_Importer.php [hunk 3]
```diff
@@ -118,24 +118,98 @@ function _generateCandidatesQuery($ScanTypes)
...
+                        $scantype,
+                        's.ID'
+                    )
+                    .     ') '
+                    . '  WHEN 0 '
+                    . '    THEN "No selected file" '
+                    . '  ELSE "Unknown: multiple Selected files"'
```
Comment (cmadjar) [inline tools/CouchDB_MRI_Importer.php:178]:
```suggestion
                    . '  ELSE "Unknown: multiple selected files"'
```

File: tools/CouchDB_MRI_Importer.php [hunk 4]
```diff
@@ -118,24 +118,98 @@ function _generateCandidatesQuery($ScanTypes)
...
+     * @param string $scanType     name of the scan type.
+     *
+     * @return string built query.
+     */
+    function _getQueryForSelectedFiles($whatToSelect, $scanType)
+    {
+        return "SELECT $whatToSelect "
+             . 'FROM files f '
+             . 'LEFT JOIN mri_scan_type msc ON (f.AcquisitionProtocolID=msc.ID) '
+             . 'LEFT JOIN files_qcstatus fqs USING (fileid) '
```
Comment (cmadjar) [inline tools/CouchDB_MRI_Importer.php:207]:
```suggestion
             . 'LEFT JOIN files_qcstatus fqs USING (FileID) '
```

**Review by cmadjar — CHANGES_REQUESTED** [review]
@jesscall this all looks good to me. I just noticed a few inconsistencies on how the result of the query would be labelled to resolve (sometimes camel case syntax is used, other times lower case). I went with the lower case suggestion but I don't have a strong preference on which convention to use as long as it looks the same ;).

I do not have a CouchDB set up to try the code. Maybe we could ask someone with CouchDB set up to test your PR on Thursday at the imaging meeting?

**Comment by jesscall** [comment]
@cmadjar Yes, sounds good. I could also ask someone from CCNA to test.

@pierre-p-s @CamilleBeau does one of you have time to test this ?

**Comment by pierre-p-s** [comment]
Getting this error when running the script

Screen Shot 2021-07-08 at 10 11 00 AM

**Comment by ridz1208** [comment]
@pierre-p-s the issue you are having seems unrelated to the PR. Are you sure you don't have an override that is not up to date and causing this error?

**Comment by pierre-p-s** [comment]
> @pierre-p-s the issue you are having seems unrelated to the PR. Are you sure you don't have an override that is not up to date and causing this error?

I tried again with rb data and I m still getting the same error

**Comment by jesscall** [comment]
@pierre-p-s sorry about that, should be good now

**Comment by pierre-p-s** [comment]
I am getting this error

Screen Shot 2021-07-28 at 2 56 23 PM

PHP:

Screen Shot 2021-07-28 at 2 57 35 PM

**Comment by pierre-p-s** [comment]
I tried to rerun and it works fine now... No idea what happened sorry about that

**Review by pierre-p-s — APPROVED** [review]

**Review by cmadjar — APPROVED** [review]
LGTM
