### PR TITLE
[media] fixes permissions. Allows media_read to download, renames "Delete" to "Hide".

### LINKED ISSUE #9162: [media] Permission names need revising
The `media` module permissions are the following:

- `Media: Edit/Upload/Delete Candidate Media Files`
- `Media: View/Download Candidate Media Files`

Users with `Media: View/Download Candidate Media Files` are able to view files but do not have the option to download them; even their own uploads.

Only users with the `Media: Edit/Upload/Delete Candidate Media Files` can download. 
However, I do not see a `Delete` feature on the v26 VM. There is a `Hide File` feature which can be listed instead.

The current names are not accurately reflecting the permission scopes.

### PR DESCRIPTION
**Pull request by racostas**
## Brief summary of changes

Allows the `media_read` permission to actually download (see) the files. The permission in this descriptions stats `Media: View/Download Candidate Media Files` but was not actually allowing to download (see) the documents.

`media_write` was substituted by `media_read` in the corresponding cases.

The permission `Media: Edit/Upload/Delete Candidate Media Files` is renamed to `Media: Edit/Upload/Hide Candidate Media Files` since we are not able to Delete files but to Hide they.
 
- [x] Have you updated related documentation?

#### Testing instructions (if applicable)

1. Go to the media module with a user having only the `media_read` permission.
2. You should be now capable of downloading (seeing) the files.
3. As admin go to edit candidate and see the permission `Media: Edit/Upload/Delete Candidate Media Files` is renamed to `Media: Edit/Upload/Hide Candidate Media Files` .
4. The rest of the functionalities in the module should be rest unchangeable. 

#### Link(s) to related issue(s)

* Resolves #9162

### CODE REVIEW

File: SQL/0000-00-02-Permission.sql [hunk 1]
```diff
@@ -33,7 +33,7 @@ CREATE TABLE `permissions` (
       'View/Create/Edit',
       'Create/Edit',
       'Edit/Upload',
-      'Edit/Upload/Delete'),
```
Comment (driusan) [inline SQL/0000-00-02-Permission.sql:36]: I don't think we want to change this? This is the generic category used for all module permissions.

@ridz1208

Comment (ridz1208) [reply SQL/0000-00-02-Permission.sql:36]: @racostas @driusan I'm okai with changing it if it's the only module using it.

Or, to be safe, just create a new one

Comment (racostas) [reply SQL/0000-00-02-Permission.sql:36]: @driusan , @ridz1208 I'm fine with both solutions. Here the considerations:
1. The only module that is using this permission it's in facts publication.
2. We can create a new permission and leave the old one, just the already existing permission will be there but not used in any other part.
3. We should consider also that some projects might be using this permission (projects that we might not aware)

I just want to reconfirm with you. After this note do we want to leave the old permission there and create a new one or should we modify it since it's "the only module" that its using it ?

Comment (ridz1208) [reply SQL/0000-00-02-Permission.sql:36]: @racostas Create a new one please

Comment (racostas) [reply SQL/0000-00-02-Permission.sql:36]: great !

File: modules/media/ajax/FileUpload.php [hunk 2]
```diff
@@ -88,7 +88,7 @@ function uploadFile()
     $db     = \NDB_Factory::singleton()->database();
     $config = NDB_Config::singleton();
     $user   =& User::singleton();
-    if (!$user->hasPermission('media_write')) {
+    if (!$user->hasPermission('media_read')) {
```
Comment (ridz1208) [inline modules/media/ajax/FileUpload.php:91]: @racostas why is uploading being changed to read ?

Comment (racostas) [reply modules/media/ajax/FileUpload.php:91]: It's looks as typo/bug from my side :) but will retest before

**Comment by racostas** [comment]
should be good now

**Review by ridz1208 — APPROVED** [review]

**Comment by driusan** [comment]
@racostas Is there an SQL patch missing for existing projects?

**Comment by racostas** [comment]
> @racostas Is there an SQL patch missing for existing projects?

I think we should update it, yes, while the functionality will be no affected the way its now. For been consistent we should rename the "front name" of the permission in the existing projects yes.

Should this be include in `/SQL/New_patches` or in `SQL/Release_patches/25.0_To_26.0_upgrade.sql`, or both ?
