### PR TITLE
[Configuration] Fix issue where a Project could not be added without subproject data

### LINKED ISSUE #5511: [Configuration] Creating new project with no affiliated subprojects gives an error
When trying to create a new project from the configuration module. if no subprojects are selected the error `Failed to save, same name already exist!` pops up in red however

1. that error is incorrect, the name does not already exist
2. the new project gets registered even though the error pops up, no subprojects are affiliated with the newly created project.

### PR DESCRIPTION
**Pull request by johnsaigle**
## Brief summary of changes

Projects can now be added without requiring that subproject data be configured at the same time. This error was encountered during v.22 release testing.

This PR also refactors the file and adds accessor methods to the Project class to make the code easier to maintain going forward as well as to take advantage of typing.

#### Links to related tickets (GitHub, Redmine, ...)

* Resolves #5511

### CODE REVIEW

**Comment by johnsaigle** [comment]
@ridz1208 Requesting your review because you found the bug during testing.

File: modules/configuration/ajax/updateProject.php [hunk 1]
```diff
@@ -22,79 +22,55 @@
...
-);
+}
 
 // Compare submitted values with DB values.
 // It's important not to delete and reinsert the values due to delete cascades on
 // tables referencing project_subproject_rel in the database.
-$subprojectIDs = $_POST['SubprojectIDs'] ?? array();
 if (empty($subprojectIDs)) {
-    http_response_code(400);
+    http_response_code(200);
```
Comment (ridz1208) [inline modules/configuration/ajax/updateProject.php]: 200 ?? not 400 ?

Comment (johnsaigle) [reply modules/configuration/ajax/updateProject.php]: I added a code comment to clarify
