### PR TITLE
[Install] Fix crash due to unbound variable access

### LINKED ISSUE #5640: [install] after pushing 21 into 22. "unbound variable" in install.sh
[install] after merging 21 into 22. "unbound variable" in install.sh

### PR DESCRIPTION
**Pull request by johnsaigle**
## Brief summary of changes

Fixes a bug where the script would crash due to `$projectname` being accessed before it is initialized.

#### Testing instructions (if applicable)

1. Run the install script. 

#### Links to related tickets (GitHub, Redmine, ...)

* Fixes #5640

### CODE REVIEW

File: tools/install.sh [hunk 1]
```diff
@@ -176,6 +176,7 @@ echo "Ubuntu distribution detected."
         echo $yn | tee -a $LOGFILE > /dev/null
         case $yn in
             [Yy]* )
+                export projectname=""
```
Comment (driusan) [inline tools/install.sh]: Why is this exported?

Comment (johnsaigle) [reply tools/install.sh]: I was getting an error without putting that keyword in front. I'm not that familiar with bash in this regard.

Do you know whether `declare` would work better?

Comment (driusan) [reply tools/install.sh]: if you were getting an error without it it's fine, I'll merge it. It just looks out of place.
